### ISSUE TITLE
fetchToken() is not compatible with Slim's cookie encryption

### ISSUE THREAD

**Issue by aquariman** [tuupola/slim-jwt-auth#10]
For example, the return value for `fetchToken()` is `return $_COOKIE[$this->options["cookie"]];`, but this direct access of $_COOKIE invalidates Slim's cookie helper, including cookie encryption. This makes it impossible to use encrypted cookies for storing tokens. Shouldn't the return statement be: `return $this->app->getCookie($this->options["cookie"])` ?

**Comment by tuupola** [comment]
This should be fixed in dev-master now. Thanks for the heads up!

**Comment by aquariman** [comment]
No problem! Thanks for the fast response.

**Comment by tuupola** [comment]
Also released as 1.0.1.
