### ISSUE TITLE
Token does not expire

### ISSUE THREAD

**Issue by lfelisiak** [tuupola/slim-jwt-auth#102]
HI, my tokens are not expiring... although they have the default exp set at now+2hours, I'm using a token that had expired 36 hours ago... in the verify method it returns false, but the middleware does not returning any complain about the expiracy... How can I solve this?

**Comment by lfelisiak** [comment]
Solved it this way...
```
"callback" => function ($request, $response, $arguments) {
			return JWTAuth::verifyToken(str_replace('Bearer ', '', $request->getServerParams()['HTTP_AUTHORIZATION']));
		}
```

**Comment by tuupola** [comment]
Which version are you using?

**Comment by tuupola** [comment]
I just tested with latest and expired token returns 401 as expected.

**Comment by lfelisiak** [comment]
the latest, could you provide me an example of correct usage?

**Comment by tuupola** [comment]
[README](https://github.com/tuupola/slim-jwt-auth/blob/3.x/README.md) explains the available settings and [Slim API Skeleton](https://github.com/tuupola/slim-api-skeleton/blob/master/config/middleware.php) has an example of typical use case.

**Comment by lfelisiak** [comment]
Yes, I followed the readme example, but without luck, same for doing a fresh install, slim v3 and latest slim jwt
```

$app->add(new \Slim\Middleware\JwtAuthentication([
		// The secret key
		"secret" => SECRET,
		"secure"=>false,
		"rules" => [
			new \Slim\Middleware\JwtAuthentication\RequestPathRule([
				// Degenerate access to '/api'
				"path" => "/api",
				// It allows access to 'login' without a token
				"passthrough" => [
					"/api/v1/authenticate",
					"/api/v1/register/",
					"/api/v1/login"
				]
			])
		],
		"callback" => function ($request, $response, $arguments) {
			return JWTAuth::verifyToken(str_replace('Bearer ', '', $request->getServerParams()['HTTP_AUTHORIZATION']));
		}
	]));
```

**Comment by tuupola** [comment]
Ok, could you copy paste here an expired token together with the secret which the middleware says is valid.

**Comment by lfelisiak** [comment]
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJoZWFkZXIiOnsiaWQiOiJsZmVsaXNpYWsxIiwidXNlciI6ImxmZWxpc2lhazEifSwicGF5bG9hZCI6eyJpYXQiOiIyMDE4LTAzLTA2IDAzOjUwOjU1IiwiZXhwIjoiMjAxOC0wMy0wNiAwNDo1MDo1NSJ9fQ.HC__PyNMpV3JiTvp_WYftKkrEXJ0EMLeYCHgVPKv03Q` 
`20saghadesignfinanciera18`

**Comment by tuupola** [comment]
Payload of above token is:

```json
{
  "header": {
    "id": "lfelisiak1",
    "user": "lfelisiak1"
  },
  "payload": {
    "iat": "2018-03-06 03:50:55",
    "exp": "2018-03-06 04:50:55"
  }
}
```

The `iat` and `exp` claims should be seconds since EPOCH. For example `"exp" : 1300819380`.

http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html

> A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds. This is equivalent to the IEEE Std 1003.1, 2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in which each day is accounted for by exactly 86400 seconds, other than that non-integer values can be represented. See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.

**Comment by lfelisiak** [comment]
`
{
"header": {
    "id": "lfelisiak1",
    "user": "lfelisiak1"
  },
  "payload": {
    "iat": 1520347323,
    "exp": 1520347383
  }
}
`
converting it to seconds does not work either, the `strtotime() `indicates that **exp** is set at 1 minute after **iat**  time, Only works with the verification inside callback.

**Comment by tuupola** [comment]
Also your payload looks bit weird. You probably want something like:

```json
{
  "id": "lfelisiak1", 
  "user": "lfelisiak1",
  "iat": 1520347323, 
  "exp": 1520347383 
} 
```

https://jwt.io/introduction/

In other words there is no expiration because the token does not have`exp` claim.  It does have `payload.exp` but that is not where it is expected to be.

**Comment by lfelisiak** [comment]
I tooked your JWT package from [Here](https://github.com/ManuelGil/REST-Api-with-Slim-PHP) it seems that the author of this, have used it in a wrong way. I'll update soon if I can correct this issue
