### ISSUE TITLE
token usable even if expired

### ISSUE THREAD

**Issue by belpha** [tuupola/slim-jwt-auth#104]
After the expiration time, the token is still considerate usable.
I checked the result with `verifyToken` method and it returns false, that is correct, but the application simply ignore it.
I read on web that I should set `CACHE_DRIVER = file` but where I can set it? I need step-by-step help.
Thank you!

**Comment by tuupola** [comment]
Please provide an example token together with a key for testing. You can use  dummy key such as `supersecretkeyyoushouldnotcommittogithub`.

**Comment by belpha** [comment]
token
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJoZWFkZXIiOnsiaWQiOiJmYWJyaXppbyIsInVzZXIiOiIkMnkkMTAka0JtSmVDWEx0SUpxRTZaUnI5U2VkLk9FNUxVOGlsUzN0OHRBSjdmOHc1UGtTOVUwN2ZWTjYifSwicGF5bG9hZCI6eyJpYXQiOiIyMDE4LTAzLTE0IDA3OjU4OjQ1IiwiZXhwIjoiMjAxOC0wMy0xNCAwOTo1ODo0NSJ9fQ.r7O6Jm1nHjvdYNeEXbhKv4hdNPyBTg1VQvrHAGwCpTM`


key
`Zgg5DiUW6XHADC2VCayaW91ksCwEnwQM`



and here the method to create the token
```
public static function getToken($id, $user) {
		$secret = SECRET;
		// date: now
		$now = date('Y-m-d H:i:s');
		// date: now +2 hours
		$future = date('Y-m-d H:i:s', mktime(date('H') + 2, date('i'), date('s'), date('m'), date('d'), date('Y')));
		$token = array(
			'header' => [ // User Information
				'id' => $id, // User id
				'user' => $user // username
			],
			'payload' => [
				'iat' => $now, // Start time of the token
				'exp' => $future // Time the token expires (+2 hours)
			]
		);
		// Encode Jwt Authentication Token
		return JWT::encode($token, $secret, "HS256");
	}
```

**Comment by tuupola** [comment]
The payload of your token is:

```
{
  "header": {
    "id": "fabrizio",
    "user": "$2y$10$kBmJeCXLtIJqE6ZRr9Sed.OE5LU8ilS3t8tAJ7f8w5PkS9U07fVN6"
  },
  "payload": {
    "iat": "2018-03-14 07:58:45",
    "exp": "2018-03-14 09:58:45"
  }
}
```

This is not a valid JWT token. For example there is no `exp` claim. Instead there is `payload.exp`.  Also the value of `exp` is not valid. It should be a unix timestamp not a string.  Correct token payload in your case would looks something like:

```
{
  "id": "fabrizio", 
  "user": "$2y$10$kBmJeCXLtIJqE6ZRr9Sed.OE5LU8ilS3t8tAJ7f8w5PkS9U07fVN6",
  "iat": 1520347323, 
  "exp": 1520347383 
} 
```

For more info see https://github.com/tuupola/slim-jwt-auth/issues/102.

**Comment by belpha** [comment]
OK so I'll change the method like that?
```
public static function getToken($id, $user) {
		$secret = SECRET;
		// date: now
		$now = time();
		// date: now +2 hours
		$future = time()+(2*60*60);
		$token = array(
			'id' => $id, // User id
			'user' => $user, // username
			'iat' => $now, // Start time of the token
			'exp' => $future, // Time the token expires (+2 hours)
		);
		// Encode Jwt Authentication Token
		return JWT::encode($token, $secret, "HS256");
	}
```
I'll be back soon with the result

**Comment by belpha** [comment]
It works like a charm, thank you!

**Comment by luizcarlospedrosogomes** [comment]
tanks guys
