### ISSUE TITLE
All tokens result in "Signature verification failed"

### ISSUE THREAD

**Issue by gilphilbert** [tuupola/slim-jwt-auth#105]
I've implemented this in my web app but I just can't get authorization to work. Every key that's generated fails to validate and I can't work out why.

This is my middleware:
```
$app->add(new Tuupola\Middleware\JwtAuthentication([
  "secret" => "fearlex",
  "header" => "X-Token",
  "regexp" => "/(.*)/",
  "path" => ["/api","/admin"],
  "attribute" => "userToken",
  "secure" => false,
  "error" => function ($response, $arguments) {
    $data["status"] = "error";
    $data["message"] = $arguments["message"];
    return $response
        ->withHeader("Content-Type", "application/json")
        ->getBody()->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
  }
]));
```

This is a key that's generated (using fearlex)

> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJleHAiOjE1MjEyNjk2ODB9.pD4gvDBn3M63SqHPxcf4-NkbD2CXGjy7Lt2Xdn6BG7U

I put it into https://jwt.io/ and the signature is not valid, which explains why JWT won't validate it. The question is; why are the keys invalid?

I read one of your other replies (https://github.com/tuupola/slim-jwt-auth/issues/11#issuecomment-146551509) which includes a valid token and this decodes fine. It's only the tokens created on my machine that are invalid.

Any help would be appreciated!

**Comment by tuupola** [comment]
I just tested your token (note that it is a token, not a secret key):

> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJleHAiOjE1MjEyNjk2ODB9.pD4gvDBn3M63SqHPxcf4-NkbD2CXGjy7Lt2Xdn6BG7U

in jwt.io and it validated ok when using the secret key `fearlex`.

**Comment by gilphilbert** [comment]
I realised my error too late - my code generating the token was incorrect. Fixed that and now it's working nicely.

Thanks for the fast response though!
