### ISSUE TITLE
Routes Unprotected Decode

### ISSUE THREAD

**Issue by elvispdosreis** [tuupola/slim-jwt-auth#106]
is there any way I can decode the token even on wheels that are not protected. for example in the "**/api/report**"

because I have some routes that do not need to be protected anymore if it has a user in the token I show a different information

```
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "path" => ["/api"],
    "ignore" => [
        "/api/auth/login",
        "/api/report"
    ],
    "secret" => 'xxxyyyxxx',
    "before" => function ($request, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    }
]));
```

**Comment by tuupola** [comment]
With this middleware no. It is all or nothing, there is no middleground. However you could grab the token from the request header in `/api/report` and parse it yourself while ignoring any possible errors. Under the hood the middleware users [firebase/php-jwt](https://github.com/firebase/php-jwt) so it's decoding functions are already available.

```php
use \Firebase\JWT\JWT;

$payload = JWT::encode($token, "supersecretkeyyoushouldnotcommittogithub");
```
