### ISSUE TITLE
Can't get the Authorization to work.

### ISSUE THREAD

**Issue by fearlex** [tuupola/slim-jwt-auth#11]
I love the idea behind slim-jwt-auth and i'm trying to use it for my API, but i'm completely stuck trying to get my supersecret key to even validate.

Somehow it is not clear to me, how to properly pass the secret key to the Middleware for it to properly authenticate it, and respond.

I already added the configuration needed to the .htaccess.

Maybe i'm doing something wrong ? Do i need to encode the secret pass first at http://jwt.io/ ??

I have spent hours trying to understand how to properly validate this and nothing, if you can kindly point me in the right direction, i will most likely appreciate it, as it is not clear in the docs.

Thank you so much !

**Comment by tuupola** [comment]
You pass the secret key for verifying signature in the `secret` parameter.

```php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub"
]));
```

I do not know how you generated the token, but looking at the example url above the header it tries to send is.

```
Authorization: Bearer r8uGz9YQFPLdmWQBHRU9eNYe2j3FP4rLQ9NgrShQTBv7FMxjaXnjhJcvUkXeh7gS
```

The token part [is not a valid](http://jwt.io/?value=r8uGz9YQFPLdmWQBHRU9eNYe2j3FP4rLQ9NgrShQTBv7FMxjaXnjhJcvUkXeh7gS) JWT.  

Header with valid example JWT token looks something like below. You can also [verify this](http://jwt.io/?value=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJsZXlzIFJlc2NvIiwiYWRtaW4iOnRydWV9.Rvsr4CScemkXpY0qvA21iF1hD07yGiGZJSo9REoXYcE). Token is signed using secret `fearlex` (you need to write that in the verify box).

```
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXJsZXlzIFJlc2NvIiwiYWRtaW4iOnRydWV9.Rvsr4CScemkXpY0qvA21iF1hD07yGiGZJSo9REoXYcE
```

Middleware itself expects to find the token in either the `Authorization: Bearer` header or cookie named `token`.

**Comment by fearlex** [comment]
Thank you so much, your response help clarify a few things. I appreciate you taking your time to help and to build such an amazing tool.

Thanks again.
