### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by DaniyalM** [tuupola/slim-jwt-auth#113]
Below is my code which is working fine locally but after deployment the middleware of tuupola/slim-jwt-auth and slim-basic-auth raising exceptions when i am removing these two middlewares every thing is working fine..
please guide me on this..
use Tuupola\Middleware\HttpBasicAuthentication;
 
$container = $app->getContainer();
$container['logger'] = function($c) {
    $logger = new \Monolog\Logger('my_logger');
    $file_handler = new \Monolog\Handler\StreamHandler("../logs/app.log");
    $logger->pushHandler($file_handler);
    return $logger;
};
 
$container["jwt"] = function ($container) {
    return new StdClass;
};
 
$app->add(new \Slim\Middleware\JwtAuthentication([
 "path" => "/",
    "logger" => $container['logger'],
    "secret" => "key",
    "rules" => [
        new \Slim\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/",
            "passthrough" => ["/token", "/not-secure", "/home"]
        ]),
        new \Slim\Middleware\JwtAuthentication\RequestMethodRule([
            "passthrough" => ["OPTIONS"]
        ]),
    ],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    },
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
 
$app->add(new \Slim\Middleware\HttpBasicAuthentication([
    "path" => "/api/token",
    "users" => [
        "user" => "password"
    ]
]));
 
 
$app->add(new \Tuupola\Middleware\Cors([
    "logger" => $container["logger"],
    "origin" => ["*"],
    "methods" => ["GET", "POST", "PUT", "PATCH", "DELETE"],
    "headers.allow" => ["Authorization", "If-Match", "If-Unmodified-Since"],
    "headers.expose" => ["Authorization", "Etag"],
    "credentials" => true,
    "cache" => 60,
    "error" => function ($request, $response, $arguments) {
        return new UnauthorizedResponse($arguments["message"], 401);
    }
]));

Composer.json

{
    "require": {
       
        "projek-xyz/slim-monolog": "^0.1.6",
        "tuupola/cors-middleware": "^0.5.2",
        "tuupola/base62": "^0.10.0",
        "firebase/php-jwt": "^5.0",
        "slim/slim": "^3.0",
        "tuupola/slim-jwt-auth": "^2.4",
        "tuupola/slim-basic-auth": "^2.3"
    }
}

**Comment by tuupola** [comment]
What do the Exceptions says? Ie. what is the error message?

**Comment by DaniyalM** [comment]
error callback is not even invoked as you can see in the code and their is no log in logged file either as i said above by just commenting (\Slim\Middleware\JwtAuthenticationand)   code the application is working fine..

this method is causing problem ,when i am removing this chuck of code application is working fine 


this code working perfectly in localhost but causing errors in remote host..


$app->add(new \Slim\Middleware\JwtAuthentication([
 "path" => "/",
    "logger" => $container['logger'],
    "secret" => "key",
    "rules" => [
        new \Slim\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/",
            "passthrough" => ["/token", "/not-secure", "/home"]
        ]),
        new \Slim\Middleware\JwtAuthentication\RequestMethodRule([
            "passthrough" => ["OPTIONS"]
        ]),
    ],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    },
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));

**Comment by tuupola** [comment]
If there is an Exception the middleware error callback will not be excecuted. Error callback is only for authentication errors. If you don't see it in the browser, you can look at the PHP error log to see the exception message. You might also want to check this:

https://github.com/tuupola/slim-jwt-auth#security

**Comment by DaniyalM** [comment]
nice work by tuupola its done thank you
