### ISSUE TITLE
Call Middleware after Verification

### ISSUE THREAD

**Issue by citadelnetworks** [tuupola/slim-jwt-auth#116]
I would like to do the following

Verify Token --> Call Middleware no matter what the result is (as long it's not error)

How would I go about doing this?

 I tried with the before parameter and didn't get anywhere. 

Reason for this is that I'm using this on a website, so I don't want people getting plain 401 errors. I want them to be redirected to the login page or for the backend API to be actually given the 401 error, which  I can do in the middleware by calling the route name.

Thank You

**Comment by tuupola** [comment]
If you want to redirect to a page when authentication fails you can use the [error callback](https://github.com/tuupola/slim-jwt-auth#error). For example something like:

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub",
    "path" => ["/"],
    "ignore" => ["/login"],
    "error" => function ($response, $arguments) {
        return $response
            ->withHeader("Location", "/login")
            ->withStatus(301);
    }
]));
```

**Comment by citadelnetworks** [comment]
Is there a way to call another middleware JWT finishes no matter what the outcome is?

**Comment by tuupola** [comment]
Slim itself calls the [next middleware](https://www.slimframework.com/docs/v3/concepts/middleware.html) when one middleware finishes successfully. I have a feeling that this is an XY problem. What are you trying to achieve?

**Comment by citadelnetworks** [comment]
So basically I have the following routes

/login
/register
/home
/api/login
/api/register

The /login, /register, and /home are just normal HTML pages, but the /api/login and /api/register are both APIs as you probably guessed. The JWT auth is added to the entire application. Here is what I do with my session middleware

User is not logged in and visits /home, JWT auth declares that they have no token, JWT calls the next middleware, Bear. Bear will determine the route name of the request and ultimately decide what to do.

So in the case above, Bear will do a redirect to /login. However, if the user tries to visit /api/login, Bear will return a 401 with no redirect. 

Bear will also do the following. When the user visits a page like /admin, Bear will determine when if the user is an admin by using the decoded token information and querying the database.

I can't get JWT Auth to call the next middleware no matter how hard I try. I'm guessing there is a way to do this and I'm looking for the correct parameter to use.

I hope this makes sense.

**Comment by tuupola** [comment]
I don't really follow. But in general middlewares do not call next middleware. Slim framework itself calls the next middleware. Next middleware is not called if an exception is thrown. If you do not want to respond 401 when authentication fails you could return for example response with status 200 from the error callback.

**Comment by citadelnetworks** [comment]
Alright, do you know why in the error `$response->withRedirect('/login');` doesn't work but `$response->           withHeader("Location", "/login")->withStatus(301)` works?

**Comment by tuupola** [comment]
[This patch](https://github.com/slimphp/Slim/pull/2345
) in Slim and the fact the the response error handler gets already has 401 status set. Thus you must set the 301 manually.

**Comment by citadelnetworks** [comment]
Ah thank you so much. I hate to bombard you with questions but last question haha

So my token did get encoded correctly, if I put the secret and token into jwt.io it says signature verified.

However, JWT auth can't seem to verify it.

Here is the code

```php
$token = JWT::encode($payload, $key, 'HS512');
```

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
  'path' => ['/chat'],
  'ignore' => ['/invite/*', '/hermes/login', '/hermes/register'],
  'cookie' => 'BlackFire-Auth',
  'secret' => getenv('JWT_SECRET'),
  'algorithm' => ['HS512']
]));
```

**Comment by tuupola** [comment]
Make sure your `$key` and `secret` settings match.

**Comment by citadelnetworks** [comment]
They do the $key is 
```php
  $key = getenv('JWT_SECRET');
```

and the assign cookie is

```php
      setcookie('BlackFire-Auth', $token, time()+86400, '/', '.blackfire.chat', TRUE, FALSE);
```

**Comment by tuupola** [comment]
Make sure the token is actually in the cookie. [Slim forums](https://discourse.slimframework.com/) or Slack are better place for general help. This is for bug reports.

**Comment by citadelnetworks** [comment]
Alright thank you so much!
