### ISSUE TITLE
Ignore rules not working when path not given

### ISSUE THREAD

**Issue by benmajor** [tuupola/slim-jwt-auth#118]
Firstly, thanks for the great lib.

Unfortunately, I seem to be hitting a bit of a problem, and I can't seem to figure out what's wrong. I have installed and configured the middleware as follows:

```
# Set up JWT middleware:
$app->add(new Tuupola\Middleware\JwtAuthentication([
    'ignore' => [ '/auth/login', '/auth/register' ],
    'secret' => JWT_SECRET,
    'secure' => true,
    
    'error'  => function ( $response, $arguments )
    {
        $json['statusCode'] = 401;
        $json['message']    = 'Invalid auth token.';
        
        return $response->withStatus( $json['statusCode'] )->withJson( $json );
    }
]));
```

However, when attempting to access `https://url/api/auth/register`, we still get the `401 Unauthorized` response in Postman:

![](https://i.imgur.com/L0CyAoj.png)

Please note that `/api` is a physical directory, not implemented with routes.

What am I missing? Thanks.

**Comment by tuupola** [comment]
Have you deployed the Slim app into `/` or `/api`? If former then the `ignore` parameter should be:

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    'ignore' => [ '/api/auth/login', '/api/auth/register' ],
    'secret' => JWT_SECRET,
    ...
]));
```

**Comment by benmajor** [comment]
No, Slim is deployed into `/api`. Commenting out the `ignore` rules correctly resolves.

**Comment by benmajor** [comment]
As an update on this, if we use the `rules` directive, it works as expected:

```
$app->add(new Tuupola\Middleware\JwtAuthentication([
    //'ignore' => [ '/auth/login', '/auth/register' ],
    'rules'  => [
        new Tuupola\Middleware\JwtAuthentication\RequestPathRule([
            'ignore' => [ '/auth/register' ]
        ])
    ],
    'secret' => JWT_SECRET,
    'secure' => true
]));
```

**Comment by tuupola** [comment]
What happens if you include the `path` parameter?

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    'path' => [ '/' ],
    'ignore' => [ '/api/auth/login', '/api/auth/register' ],
    'secret' => JWT_SECRET,
    ...
]));
```

**Comment by benmajor** [comment]
Thanks, including `path` works as expected! Rather confusing though, since the `rules` work without `path`. What is the reason for this?

**Comment by tuupola** [comment]
Ok. It is a bug with how default parameters are handled. Thanks for the heads up!

**Comment by benmajor** [comment]
Okay, no problem, glad I could help.
