### ISSUE TITLE
Storing secret key as an environment variable

### ISSUE THREAD

**Issue by havok1305** [tuupola/slim-jwt-auth#119]
Hello, I'm trying to use your lib with Slim and I'm having some trouble with storing the secret key as an environment variable as sugested in the docs. I have a middleware to read a file where some data is stored (including the secret key for my token) and add the data to the environment variables, then the token middleware is executed to validate the request token. The problem is, by the time the token middleware is executed, the environment variable is empty. I'm aware that Slim's middlewares use LIFE (last in first executed) order of execution but I can't seem to find the right way.
Here is an example:

```
$app->add(new \Slim\Middleware\JwtAuthentication([
    "rules" => [
        new Slim\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/",
            "passthrough" => ["/auth"],
        ]),
        new Slim\Middleware\JwtAuthentication\RequestMethodRule([
            "ignore" => ["OPTIONS"]
        ])
    ],
    "secret" => getenv("SECRETKEY"), // Getting empty value
    "error" => function ($request, $response, $arguments) {
        $data["status"] = false;
        $data["message"] = $arguments["message"];
        return $response->withJson($data);
    }
]));

$app->add(function($request, $response, $next){
   //parses file containing the data
   putenv("SECRETKEY");
   $response = $next($request, $response);
   return $response;
});
```
When the request is made, I get the message "Key may not be empty".

Any suggestion?

**Comment by tuupola** [comment]
Is there a need to do the `putenv()` in a middleware? You could also set the environment before doing `$app->run()`. For example in the example below Dotenv package is used for setting the environment:

https://github.com/tuupola/slim-api-skeleton/blob/master/app.php#L22-L23

**Comment by havok1305** [comment]
Yes, because I need to read the file based on some header passed on the request, so the `putenv()` needs to be executed inside a middleware.

**Comment by tuupola** [comment]
Ok. Not really sure. You could try debug it with using a global variable instead of environment. Just to be sure, is that how you really call putenv in the code? Code above sets an empty value to `SECRETKEY`. To set some value it should be:

```php
putenv("SECRETKEY=supersecretkeyyoushouldnotcommittogithub");
```

**Comment by tuupola** [comment]
Or maybe this: Now the middleware is initialised during `$app->add()`call when the environment is still empty. If you use container and factories the middleware is initialised when it is first called and the `SECRETKEY` should be there. See for example:

https://github.com/tuupola/slim-api-skeleton/blob/master/config/middleware.php

**Comment by havok1305** [comment]
> You could try debug it with using a global variable instead of environment. Just to be sure, is that how you really call putenv in the code? Code above sets an empty value to SECRETKEY. 

In the real code it was right, there was a typo in the example.

Using containers solved the problem. Thanks mate.
