### ISSUE TITLE
$this->decodeToken failed should return 401 unauthorised

### ISSUE THREAD

**Issue by morph85** [tuupola/slim-jwt-auth#12]
Any exception that encountered in decoding token should be regarded as unauthorised, in order to cater for exceptions that is returned from JWT: ExpiredException, BeforeValidException and SignatureInvalidException. Generally malformed token should be regarded as unauthorised as well.

**Comment by tuupola** [comment]
It returns `401` now. Will do release soonish.

**Comment by morph85** [comment]
Great! Thank you.
