### ISSUE TITLE
Token not authenticating on online server but working on localhost

### ISSUE THREAD

**Issue by idlatest** [tuupola/slim-jwt-auth#122]
Hello there, this is not my first time of using slim-jwt-auth, I have used the version 2.3 before on a project and it worked well. Now the version 3 is not working on the online server, I am receiving a status code of 401 Unauthorized when on an online server but working very well on localhost. I am hosting the project on a subdomain. please, what could be the problem?

**Comment by idlatest** [comment]
I am receiving a status code of 401 Unauthorized when on an online server

**Comment by tuupola** [comment]
My guess is the PHP process in live server does not receive the `Authorization` header.
 Look for differences between the dev and production server. 

For example if live server is using FastCGI then by default [Apache does not pass credentials](https://bugs.php.net/bug.php?id=35752) to FastCGI process. You need to specifically tell FastCGI to pass the Authorization header with config:

```
FastCgiExternalServer /usr/lib/cgi-bin/php7-fcgi -host 127.0.0.1:9000 -pass-header Authorization
```

If live uses vanilla Apache make sure the required RewriteRule exists in .htaccess file.

```
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

**Comment by idlatest** [comment]
Yes, thank you for your reply. I have contacted the hosting company and they have resolved the issue. It was from their end.

**Comment by tuupola** [comment]
Great!

**Comment by applibs** [comment]
For me works only when I changed setting 'header' into 'X-Token'
