### ISSUE TITLE
How can i create rule for same path but with different method

### ISSUE THREAD

**Issue by PhouvanhKCSV** [tuupola/slim-jwt-auth#124]
Hi,

How can i do the following:
**ignore -> GET /api/projects/{projectId}/posts** (list all project's posts)
**authenticate  -> POST /api/projects/{projectId}/posts** (create new project's posts)

I have take a look at [Rule Section in Readme](https://github.com/tuupola/slim-jwt-auth#rules) but **RequestPathRule** only accept "path" and "ignore" but it is not accept "path with method"

Could someone tell me how to implement a callable in my case.

Thanks.

Ref: #68

**Comment by PhouvanhKCSV** [comment]
Close because duplicated with https://github.com/tuupola/slim-jwt-auth/issues/68

**Comment by tuupola** [comment]
Not possible with current rules but you could create your own rule. Rule must implement a [RuleInterface](https://github.com/tuupola/slim-jwt-auth/blob/3.x/src/JwtAuthentication/RuleInterface.php) ie. it should be callable. If a rule returns boolean `false` the request will not be authenticated.

```php
$app = new \Slim\App();

$app->add(new Tuupola\Middleware\HttpBasicAuthentication([
    "rules" => [
        new Tuupola\Middleware\HttpBasicAuthentication\RequestPathRule([
            "path" => "/",
            "passthrough" => ["/public"]
        ]),
        new Some\Other\CustomRule([
            "foo" => "bar"
        ])
    ]
]));
```

Check one of the [existing rules](https://github.com/tuupola/slim-jwt-auth/blob/3.x/src/JwtAuthentication/RequestMethodRule.php) for an example implementation.

**Comment by AlejoDev** [comment]
You can extend class RequestPathRule, and add code lines like this
`foreach ((array)$this->options["customRules"] as $rule) {
            $uri = "/" . $request->getUri()->getPath();
            $method = $request->getMethod();
            if ($rule["path"] === $uri && $rule["method"] === $method) {
                return false;
            }
        }` 

Where "customRules" are defined in 
`$app->add(new Tuupola\Middleware\HttpBasicAuthentication([
    "rules" => [
        new YourClassExtended([
            "customRules" => [
                    ["path" => "/system/config/data", "method" => "GET"]
                ]
        ])
    ]
]));`

It worked for me.

Greetings
