### ISSUE TITLE
I found very diffucult to implement. Finally I Dropped. You have any examples

### ISSUE THREAD

**Issue by manjeshpv** [tuupola/slim-jwt-auth#13]
Please give me some links, I don't understand the idea behind this package

**Comment by ronaldo-systemar** [comment]
Dude, go to https://github.com/tuupola/slim-jwt-auth scroll down and you can see a full sample usage of this package, nothing special.

**Comment by ronaldo-systemar** [comment]
If you are not familiarized with JWT I suggest you the following links:

https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/
http://www.jamiekurtz.com/2014/11/25/5-keys-to-web-app-token-authentication/

**Comment by tuupola** [comment]
There is quite much information of [what JWT is](https://www.google.ee/search?q=what+is+jwt) available. Also check [Learn how to use JSON Web Token](https://github.com/dwyl/learn-json-web-tokens) project. Although the example code is for Node it contains much good basic information on JWT.

**Comment by ronaldo-systemar** [comment]
I will try a shorten explanation:

* The user sends to your api user/password credentials in a specific route to authenticate (http://mydomain.com/auth/try)
* In this authentication route, you will do validations with user data like user/password length, database comparsion, etc.
* If this credentials are true, you generates a JWT and give it back to the user, storing in your application local storage or session, it's your choice where you kept the data.
* For every request the user does, you need to send the generated token in the header, as the following: Authorization Bearer {GENERATED_TOKEN}

**WHERE:**
Authorization: is the key in the header
Bearer {GENERATED_TOKEN}: is the value of Authorization key in the header

**An example looks like this:**
Authorization Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJSb25hbGRvIEpyIiwiaWF0IjoxNDQ0NDAwMjQyLCJleHAiOjE0NDUwMDUwNDIsInVpZCI6InJvbmFsZG9Ac3lzdGVtYXIuY29tLmJyIn0.ZuAR7Itp-kT7XCwuRi2TSiLA9bvWpP6WU4Wkwaj5cdc

Everytime any request is sent, JWT middleware validates if this token is OK, if **IT IS**, the middleware let the route pass, **IF NOT**, middleware rejects the request.

Take care with token expiration, sometimes credentials are ok, but expiration has gone.

**Comment by tuupola** [comment]
[Example code](https://gist.github.com/tuupola/24a8cbf5e6106bb70a01) of what @ronaldo-systemar explained abobe.

**Comment by manjeshpv** [comment]
I understand, If you provide a example project, Then programmers with minimum knowledge like me can cross-check the sample code.

What I thought initially about this package
* Its a complete package for generating and verify tokens 
* I seen `['read','write','delete']` in the code, so I thought RBAC also available.
* And I expected options comes under one middleware.

My Questions: you might add it  to faqs documentation if its meaningful
* I'm using for API security. Why Basic HTTP Authentication. 
* If you're not generating token, What is reason behind login
* Sample code is always underlying layer independent. Actual code is depending on the Token generation algorithm. OS variations(https://github.com/tuupola/slim-jwt-auth/issues/9) 

My Expectations:
* Sample Demo Code Repo https://github.com/manjeshpv/slim-jwt-auth-demo

This are issues I got, and way I followed

> tuupola/slim-jwt-auth 3.x Documentation not directly available.(I switched branch and found docs)

```sh
>  composer require slim/slim 3.x-dev
>  tuupola/slim-jwt-auth 2.0.0
```
The I created file https://github.com/manjeshpv/slim-jwt-auth-demo/commit/bf1f0b03d38c52e7aaec999c6d10cd30a3d8c2e5
`Fatal error: Class 'Slim\Slim' not found in slim-jwt-auth-demo\index.php on line 19`
Because Slim 3.x-dev come with Slim\App

`Fatal error: Class 'Slim\Middleware\HttpBasicAuthentication' not found in D:\xampp\htdocs\slim-jwt-auth-demo\index.php on line 32`
Here Installed `composer require tuupola/slim-basic-auth`

```
D:\xampp\htdocs\slim-jwt-auth-demo>composer require tuupola/slim-basic-auth
Using version dev-master for tuupola/slim-basic-auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: slim/slim[2.x-dev, 3.x-dev].
    - Can only install one of: slim/slim[3.x-dev, 2.x-dev].
    - Can only install one of: slim/slim[2.x-dev, 3.x-dev].
    - tuupola/slim-basic-auth dev-master requires slim/slim ~2.3 -> satisfiable by slim/slim[2.x-dev].
    - Installation request for tuupola/slim-basic-auth dev-master -> satisfiable by tuupola/slim-basic-auth[dev-master].
    - Installation request for slim/slim 3.x-dev -> satisfiable by slim/slim[3.x-dev].


Installation failed, reverting ./composer.json to its original content.
```
The I got to know all package are latest dev branchs
`>composer require tuupola/slim-basic-auth 2.x-dev`

Now 
GET http://localhost/slim-jwt-auth-demo/index.php/secured
```js
{"message":"token success","access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0.eyJpc3MiOiJodHRwOlwvXC9tYW5qZXNocHYuY29tIiwiYXVkIjoibW9iaWxlQXBwIiwianRpIjoiNGYxZzIzYTEyYWEiLCJpYXQiOjE0NDU2NjcxMDAsIm5iZiI6MTQ0NTY2NzE2MCwiZXhwIjoxNDQ1NjcwNzAwLCJ1c2VyX2lkIjoxLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiLCJkZWxldGUiXX0.i1oLa8YUxhf5TVFcArN3nXn-AfHIvP6V2dpFKe7ggpM"}
```

GET: http://localhost/slim-jwt-auth-demo/index.php/secured
Method Not Allowed
```sh
POST: http://localhost/slim-jwt-auth-demo/index.php/secured
Authentication: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0.eyJpc3MiOiJodHRwOlwvXC9tYW5qZXNocHYuY29tIiwiYXVkIjoibW9iaWxlQXBwIiwianRpIjoiNGYxZzIzYTEyYWEiLCJpYXQiOjE0NDU2NjcxODUsIm5iZiI6MTQ0NTY2NzI0NSwiZXhwIjoxNDQ1NjcwNzg1LCJ1c2VyX2lkIjoxLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiLCJkZWxldGUiXX0.OkaQwFkuAA3_hxq_T6RfiR2EyzVuhOb-E4p1fxYBJ94
```
```js
{"message":" success","data":"Secured Content"}
```
Now here
* With or without token route is working. no http authentication prompt
* How can I access token verified status in code , leads to error
```php
$response = array('jwt'=>$app->jwt);
```php
$app->add(new HttpBasicAuthentication([
    //"path" => "/token", // If  I comment this line auth works
    "users" => [
        "user" => "password"
    ]
]));
```

**Comment by manjeshpv** [comment]
https://github.com/manjeshpv/slim-jwt-auth-demo

Can you please fork the aboe repo and complete the implementation for me. Thanks in Advance

**Comment by tuupola** [comment]
My advice is programmers with minimum knowledge should not use JWT authentication. It is really easy to shoot yourself in the foot.

> What I thought initially about this package. Its a complete package for generating and verify tokens
> I seen ['read','write','delete'] in the code, so I thought RBAC also available. And I expected options 
> comes under one middleware.

Second column in the [README](https://github.com/tuupola/slim-jwt-auth/blob/master/README.md) says:

> It does not implement OAuth 2.0 authorization server nor does it provide ways to generate, issue or 
> store authentication tokens. It only parses and authenticates a token when passed via header or 
> cookie. This is useful, for example, when you want to use JSON Web Tokens as API keys.

In any case Github issues in not place for general programming help. Stackoverflow is better place for such questions. Check especially [JWT](http://stackoverflow.com/questions/tagged/jwt), [Slim](http://stackoverflow.com/questions/tagged/slim) and [Composer](http://stackoverflow.com/questions/tagged/composer-php) tags.

**Comment by manjeshpv** [comment]
Thank you. But I have to do. Sorry for making u trouble. because of my lack of knowledge.

**Comment by inventr** [comment]
@manjeshpv to create your endpoint token you must use 
```
use Firebase\JWT\JWT;

$time = time();
$key = 'your_secret_key_here';
$token = [
    "iss" => 'example',
    "iat" => $time, 
    "exp" => ($time + 604800),
    "scope" => ["read", "write", "delete"]
    ];

$jwt = JWT::encode($token, $key);
```
then everything magically work

**Comment by tuupola** [comment]
I would replace the word *"must"* with *"can"*. It is not mandatory to use `Firebase\JWT`. You can use anything which produces valid JWT.

**Comment by inventr** [comment]
You are right , the recommendation is to be used with tools that are already.
