### ISSUE TITLE
http-factory dependency tree

### ISSUE THREAD

**Issue by solcik** [tuupola/slim-jwt-auth#130]
This commit cc23885 introduced a lot of dev-dependencies, because of wrong entry in dependencies.

Fix: https://github.com/tuupola/http-factory/pull/3

Difference to 3.0.0
  - Removing webmozart/assert (1.3.0)
  - Removing theseer/tokenizer (1.1.0)
  - Removing sebastian/version (2.0.1)
  - Removing sebastian/resource-operations (1.0.0)
  - Removing sebastian/recursion-context (3.0.0)
  - Removing sebastian/object-reflector (1.1.1)
  - Removing sebastian/object-enumerator (3.0.3)
  - Removing sebastian/global-state (2.0.0)
  - Removing sebastian/exporter (3.1.0)
  - Removing sebastian/environment (3.1.0)
  - Removing sebastian/diff (3.0.1)
  - Removing sebastian/comparator (3.0.2)
  - Removing sebastian/code-unit-reverse-lookup (1.0.1)
  - Removing psr/http-factory (1.0.0)
  - Removing phpunit/phpunit (7.3.1)
  - Removing phpunit/php-token-stream (3.0.0)
  - Removing phpunit/php-timer (2.0.0)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing phpunit/php-file-iterator (2.0.1)
  - Removing phpunit/php-code-coverage (6.0.7)
  - Removing phpspec/prophecy (1.8.0)
  - Removing phpdocumentor/type-resolver (0.4.0)
  - Removing phpdocumentor/reflection-docblock (4.3.0)
  - Removing phpdocumentor/reflection-common (1.0.1)
  - Removing phar-io/version (2.0.1)
  - Removing phar-io/manifest (1.0.3)
  - Removing myclabs/deep-copy (1.8.1)
  - Removing http-interop/http-factory-tests (0.5.0)
  - Downgrading tuupola/callable-handler (0.4.0 => 0.3.0): Downloading (100%)
  - Installing http-interop/http-factory (0.3.0): Downloading (100%)
  - Downgrading tuupola/http-factory (0.4.0 => 0.3.0): Downloading (100%)
  - Downgrading tuupola/slim-jwt-auth (3.1.0 => 3.0.0): Downloading (100%)

**Comment by tuupola** [comment]
This should be fixed now in `tuupola/http-factory:0.4.1`.

```
$ composer require tuupola/slim-jwt-auth

Using version ^3.1 for tuupola/slim-jwt-auth
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-server-handler (1.0.0): Loading from cache
  - Installing psr/http-server-middleware (1.0.0): Loading from cache
  - Installing tuupola/callable-handler (0.4.0): Loading from cache
  - Installing psr/http-factory (1.0.0): Loading from cache
  - Installing tuupola/http-factory (0.4.1): Downloading (100%)
  - Installing firebase/php-jwt (v5.0.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing tuupola/slim-jwt-auth (3.1.0): Downloading (100%)
Writing lock file
Generating autoload files
```
