### ISSUE TITLE
Can I ignore auth directly in Routes?

### ISSUE THREAD

**Issue by henriquearthur** [tuupola/slim-jwt-auth#131]
I am aware of the option `"ignore"` on the middleware options which can be used to ignore authentication in some paths.

I want to know if it is possible to ignore authentication directly on the route?

Something like this:

    $app->get('/test', function ($request, $response) {
        // ...
    })->add(IgnoreAuthentication::class);

In this example, I don't know what to put in IgnoreAuthentication class. (could be another way, this is just an example)

I have an application with many routes and not all requires authentication. It would be more organized for me to declare that on my routes file and not in the slim-jwt-auth middleware.

Thanks!

**Comment by tuupola** [comment]
No, but you could do it the other way. Add the middleware only to those routes which you want to be authenticated.

**Comment by henriquearthur** [comment]
Okay. Thank you!
