### ISSUE TITLE
token not found error even if Token header is present

### ISSUE THREAD

**Issue by lakinmohapatra** [tuupola/slim-jwt-auth#133]
`$now = new DateTime();
        $future = new DateTime("now +72 hours");
        //$future = new DateTime("now +1 minute");
        $payload = [
            "iat" => $now->getTimeStamp(),
            "exp" => $future->getTimeStamp(),
            "jti" => base64_encode(random_bytes(16)),
            'iss' => $this->appConfig['app']['url'],  // Issuer
            "sub" => $user->{self::SUBJECT_IDENTIFIER},
            "user_id" => $user->id,
            "user_role_id" => $user->user_role_id
        ];
        $secret = $this->appConfig['jwt']['secret'];
        $token = JWT::encode($payload, $secret, "HS256");`

Also i am able to decode it in angular.  
But when i am sending token in header , its showing .token not found error.
But it works on my local machine. 

Please advise.

**Comment by tuupola** [comment]
PHP process in live server probably does not receive the `Authorization` header. Look for differences between the dev and production server. 

For example if live server is using FastCGI then by default [Apache does not pass credentials](https://bugs.php.net/bug.php?id=35752) to FastCGI process. You need to specifically tell FastCGI to pass the Authorization header with config:

```
FastCgiExternalServer /usr/lib/cgi-bin/php7-fcgi -host 127.0.0.1:9000 -pass-header Authorization
```

If live uses vanilla Apache make sure the required RewriteRule exists in .htaccess file.

```
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

**Comment by lakinmohapatra** [comment]
Thanks a lot . It worked.

**Comment by tuupola** [comment]
Great!

**Comment by hernanBeiza** [comment]
Thanks! Works like a charm on Apache Server!
