### ISSUE TITLE
Please honor the headers "X-Forwarded-Proto: https" and "Https: On" ..

### ISSUE THREAD

**Issue by scones** [tuupola/slim-jwt-auth#135]
.. when evaluating `secure`

i just had a fail in the production setup, where the ssl offloading happens further up in the chain, but within our application stack.

**Comment by tuupola** [comment]
In the meanwhile, if you are only accessing over `http` you can also set `secure` to `false`.

**Comment by scones** [comment]
did that, undermines security tho

**Comment by tuupola** [comment]
Trusting arbitrary headers which anyone can set is not much more secure.

**Comment by scones** [comment]
true. it's the job of the ssl-termination-service to drop such incoming headers on non-ssl-connections.
or better yet: not to allow unsecure traffic.
