### ISSUE TITLE
Optional JWT authentication

### ISSUE THREAD

**Issue by girishkc** [tuupola/slim-jwt-auth#136]
Is there any way to authenticate the JWT only IF present?

I have a situation where `/api/places` request is available for both logged-in or not logged-in users. 
If the request is received along with the JWT, I have to provide list of public and private places, and only public places if the request is without JWT

`/api/places` with JWT  > Validate JWT
`/api/places` without JWT  > passthrough

Is it possible?

**Comment by tuupola** [comment]
You could create a custom rule which checks if token is present. If token is not present, the rule should return boolean `false` which causes request not to be authenticated.

https://github.com/tuupola/slim-jwt-auth#rules
