### ISSUE TITLE
$request->getHeader('Authorization'); returns empty causes 401

### ISSUE THREAD

**Issue by contactjavas** [tuupola/slim-jwt-auth#139]
Condition
- I use the latest `Slim` & `slim-jwt-auth` when writing this
- I've added rule in `.htaccess` as in [slim-jwt-auth documentation](https://github.com/tuupola/slim-jwt-auth#install).
- I've tried both:
  - `RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`
  - or/and `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`
- Then read about [Josh Lockhart's comment](http://help.slimframework.com/discussions/problems/711-is-slim-deleting-request-headers-fields#comment_15725134) and [PHP community comment](http://php.net/manual/en/features.http-auth.php#107642), but i don't understand :-/
- Using Insomnia REST Client, i've made sure that the Authorization header exists and i've set proper value (which i generated before) into it.

Result
- It always returns 401
- I checked then i know that `$headers = $request->getHeader($this->options["header"]);` in [this line](https://github.com/tuupola/slim-jwt-auth/blob/e50fa3cc6135abdc1b03e88c0425258a4955d01b/src/JwtAuthentication.php#L243) always returns empty. So yeah, can't use `$request->getHeader('Authorization');` (Slim didn't reach it or, it didn't reach Slim?)
- I can still get the Authorization using `$_SERVER['REDIRECT_HTTP_AUTHORIZATION']`, but `slim-jwt-auth` doesn't check it anymore right?

Expectation
- When it's still in [2.3.3](https://github.com/tuupola/slim-jwt-auth/blob/1f9fb673e4f5bb9ca4104e328aabfc2e4af38c32/src/JwtAuthentication.php#L198), it still checked the [environments](https://github.com/tuupola/slim-jwt-auth/blob/1f9fb673e4f5bb9ca4104e328aabfc2e4af38c32/src/JwtAuthentication.php#L44) which is cool.
- But start from [3.0.0-rc.1](https://github.com/tuupola/slim-jwt-auth/blob/5f0fe85fe43802f2cab50ce55e9739e6de08fb3b/src/JwtAuthentication.php#L228) it just checked the header without providing environment checking.

What do you think @tuupola ? Do you have suggestion for this?

**Comment by tuupola** [comment]
The `3.x` branch assumes the required header is provided by the PSR-7 request object. It does not try to fix non-standard cases such as `REDIRECT_HTTP_AUTHORIZATION` anymore. 

If the situation cannot be fixed with Apache / Nginx / FCGI config you could try adding a custom middleware before `slim-jwt-auth` which takes the value of `$_SERVER['REDIRECT_HTTP_AUTHORIZATION']` and inserts the value to as `Authorization` header of the request object.

**Comment by contactjavas** [comment]
Thank you for your suggestion @tuupola !
It ended up with this:
```
// Header "Authorization" patch
$app->add(function ($request, $response, $next) {
    $request = $request->withHeader('Authorization', $_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
    $response = $next($request, $response);
    return $response;
});
```

**Comment by tuupola** [comment]
Glad you fixed it!

**Comment by mahadevtwaghamare** [comment]
> Thank you for your suggestion @tuupola !
> It ended up with this:
> 
> ```
> // Header "Authorization" patch
> $app->add(function ($request, $response, $next) {
>     $request = $request->withHeader('Authorization', $_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
>     $response = $next($request, $response);
>     return $response;
> });
> ```

Thank you @contactjavas, It worked for me and saved my day
