### ISSUE TITLE
Feature request: Allow passing callables (invokable classes) to before/after/error

### ISSUE THREAD

**Issue by JanMikes** [tuupola/slim-jwt-auth#143]
Hello!

I would love to pass my callable class (with the `__invoke`) method, to the `before` option, but unfortunately it is not possible due to the type check for closure:
```
TypeError
Argument 1 passed to Tuupola\Middleware\JwtAuthentication::before() must be an instance of Closure, instance of Caloriary\Infrastructure\Authentication\UserProvider given
```

Imagine UserProvider is class something like this:
```php
final class UserProvider
{
	// ...

	public function __invoke(..) { /* $this->currentUser = some logic .. */ }      

	public function currentUser(): User
	{
		if (!$this->currentUser) {
			throw new RestrictedAccess('User is not logged in');
		}

		return $this->currentUser;
	}
}
```

Does it make sense?

I use SlimApp together with DI container, so i am not adding middlewares directly in the `app.php` or `index.php` but via config file - you might want to have look at this: https://github.com/BrandEmbassy/slim-nette-extension

Anyways thank you, for this package! Any feedback about this approach is appreciated!

**Comment by tuupola** [comment]
Yes it makes sense. I need to figure out if changing it to `callable` is a BC break. In the meanwhile have you tried if [Closure::fromCallable()](https://secure.php.net/manual/en/closure.fromcallable.php) is usable as a workaround?

**Comment by JanMikes** [comment]
Thank you for the tip with `Closure::fromCallable()`, i have tried it and unfortunately it did not work.

Mean while i implemented other middleware dependent on this one, to get my dirty job done 😄

**Comment by JanMikes** [comment]
Thnx 👍
