### ISSUE TITLE
PHP Fatal error:  Class 'Tuupola\\Middleware\\JwtAuthentication' not found

### ISSUE THREAD

**Issue by jasmin83** [tuupola/slim-jwt-auth#145]
Hi,

I have xampp installed and the php version is 5.6.

After composer installed 'tuupola/slim-jwt-auth' package, I am getting 'PHP Fatal error:  Class 'Tuupola\\Middleware\\JwtAuthentication' not found' error.

below is my code:

- In middleware.php file, I have added below code:

$app = new Slim\App;

// e.g: $app->add(new \Slim\Csrf\Guard);
$app->add(new Tuupola\Middleware\JwtAuthentication([
"path" => "/api", /* or ["/api", "/admin"] */
"attribute" => "decoded_token_data",
"secure" => false,
"secret" => "supersecretkeyyoushouldnotcommittogithub",
"algorithm" => ["HS256"],
"error" => function ($response, $arguments) {
$data["status"] = "error";
$data["message"] = $arguments["message"];
return $response
->withHeader("Content-Type", "application/json")
->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
}
]));

- In BaseTestCase.php, I have added below line:

use \Firebase\JWT\JWT;

- My composer file as below:
 "require": {
        "php": ">=5.6",
        "slim/slim": "^3.1",
        "slim/php-view": "^2.0",
        "monolog/monolog": "^1.17",
        "palanik/corsslim": "dev-slim3",
        "tuupola/slim-jwt-auth": "^2.3",
        "tuupola/cors-middleware": "^0.5.2",
        "firebase/php-jwt": "^5.0",
        "tuupola/base62": "^0.9.0",
        "tuupola/slim-basic-auth": "^2.3"
    },
"autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/",
            "tuupola/slim-jwt-auth\\": "src/"
        }
    },

When I hit API using postman, I am getting below error:
<b>Fatal error</b>:  Class 'Tuupola\Middleware\JwtAuthentication' not found in

Please suggest me to solve this issue.

Thanks.

**Comment by tuupola** [comment]
You have installed the older [2.x](https://github.com/tuupola/slim-jwt-auth/tree/2.x) version which has different namespace. Instead of `Tuupola\Middleware\JwtAuthentication` older version uses `Slim\Middleware\JwtAuthentication`.

There are some other smaller differences too. So make sure you are following the [older README](https://github.com/tuupola/slim-jwt-auth/blob/2.x/README.md).

**Comment by jasmin83** [comment]
Hi,

Thanks..now I am able to generate token.

I have a question, in slim framework 3 - how to get token from header and
authenticate.?
Please guide me.

Thanks

**Comment by tuupola** [comment]
This middleware does authentication automatically. It is the purpose if this middleware. 

If you use some other header than default `Authorization: Bearer xxxx` you might need to change the [header](https://github.com/tuupola/slim-jwt-auth#header) and [regexp](https://github.com/tuupola/slim-jwt-auth#regexp) settings though.
