### ISSUE TITLE
RequestPathRule return warning with preg_match func

### ISSUE THREAD

**Issue by erujanac** [tuupola/slim-jwt-auth#147]
Warning: preg_match():
Compilation failed:nothing to repeat at offset 1 in /vendor/tuupola/slim-jwt-auth/src/JwtAuthentication/RequestPathRule.php on line "66".

We have issue with preg_match("@^{$path}(/.*)?$@", $uri) => double quotes, it should just be added single quotes instead.

**Comment by tuupola** [comment]
What PHP version this is happening? Could not find any warnings in Travis.

https://travis-ci.org/tuupola/slim-jwt-auth

**Comment by erujanac** [comment]
Hi, 
I'm using PHP Version 7.1.16 (PHP Slim 3.11.0 framework).

This is happening when action in controller is "stopped" with die;  (and in response body of react application when accessing each endpoint of REST API).

**Comment by erujanac** [comment]
Hi,
I found what cause "warnings". It's related to my "settings" for "jwt".
I have added this  in  'ignore'    => ['**_*_**/auth/login'], and that was cousin warnings when trying to "parse" paths.
I have just remove "*" and it works just fine.

Thank you for your support,
Regards.
