### ISSUE TITLE
error $callable JWT 

### ISSUE THREAD

**Issue by ardani** [tuupola/slim-jwt-auth#15]
hi tuupola.
i use jwt auth form your repo but i have error code in here
```php
public function shouldAuthenticate()
    {
        /* If any of the rules in stack return false will not authenticate */
        foreach ($this->rules as $callable) {
            if (false === $callable($this->app)) {
                return false;
            }
        }
        return true;
    }
```
in above error function name must be callable - a string
because class $callable not implement constructor or __invoke . any have fix for that?
thanks

**Comment by tuupola** [comment]
How does your code look like?

**Comment by ardani** [comment]
when i open 
file : slim-jwt-auth/src/JwtAuthentication.php using editor phpstorm, then it showing hint error on line 133.
the message error like above.
but when code running, it is well no error at all

**Comment by tuupola** [comment]
I do not use PHPstorm myself so I have no idea why it is complaining.
