### ISSUE TITLE
Add Middleware from Class: 'Tuupola\Middleware\JwtAuthentication'

### ISSUE THREAD

**Issue by mateomu18** [tuupola/slim-jwt-auth#152]
My intention is to define a class and then add middleware in this way:
 
`$app->add(\Api\Src\Middleware\MyClass::class . ':MyMethod');`

MyMethod is a function like that:

```
public function MyMethod(){
     return  new Tuupola\Middleware\JwtAuthentication([
          "secret" => "supersecretkeyyoushouldnotcommittogithub"
     ]);
}
```

But if I do this the I get a response that says something like "you have to return something of the class ResponseInterface"

How could I fix this problem?

**Comment by tuupola** [comment]
Middlewares have to return PSR-7 `Psr\Http\Message\ResponseInterface`. In the above example the `MyClass::MyMethod` returns `Tuupola\Middleware\JwtAuthentication`.
