### ISSUE TITLE
Does it work with AWS Cognito?

### ISSUE THREAD

**Issue by ganesh35** [tuupola/slim-jwt-auth#157]
I am trying to use it with AWS Cognito it always throws this error:

```
{
    "title": "OpenSSL error: error:0906D06C:PEM routines:PEM_read_bio:no start line",
    "type": "about:blank",
    "status": 401
}
```

Is there any way I can use it?

**Comment by tuupola** [comment]
I have no idea how AWS Cognito works, never used it myself. Google [search](https://www.startpage.com/do/dsearch?query=OpenSSL+error%3A+error%3A0906D06C%3APEM+routines%3APEM_read_bio%3Ano+start+line&cat=web&pl=opensearch) suggests the error has something to do with `.pem` files.
