### ISSUE TITLE
Multiple secreet on database

### ISSUE THREAD

**Issue by dpbuzz** [tuupola/slim-jwt-auth#161]
I Mika.
Thank you for sharing this middleware, it help me a lote!!

I have an API using PHP 5.6 + SLIM + slim-jwt-auth 2.X.
The API has to conect to differents databases depending on payload "usr" data.
I tried to use "kid"payload but I guest is not implemented on v2.X
I tried to use a the configuration container to set jwt_secret="" and then a middleware acces de DB and get the secret by user like this:

$config['jwt_secret'] ='';
$app = new Slim\App(["settings" => $config]);

$app->add(new \Slim\Middleware\JwtAuthentication ([
    "secret"         => $container->get('settings')['jwt_secret']
....
]));

// get jwt_secret by usr
$app->add(function ($request, $response, $next) {
    $settings = $this->get('settings');
    // code for get "usr" from jwt payload 
    // code for get jwt_secret from database by usr
    $settings['jwt_secret']='usr_jwt_secret'
    $response = $next($request, $response);
    return $response;
});

but it seems JwtAuthentication evaluate $container->get('settings')['jwt_secret'] on loading, and nevers get the new value.

Any idea for getting a secret from database before calling JwtAuthentication?
Thanks

**Comment by tuupola** [comment]
Just noticed I have forgotten to document it, but you can pass an array of secrets to the constructor. Middleware will then choose the key based on kid claim in the token header.

```php
$app->add(new JwtAuthentication([
    "secret" => [
        "acme" =>"supersecretkeyyoushouldnotcommittogithub",
        "beta" =>"anothersecretkeyfornevertocommittogithub"
    ]
]));
```
