### ISSUE TITLE
Callbacks in middleware are ignored

### ISSUE THREAD

**Issue by MalekMartin** [tuupola/slim-jwt-auth#164]
Hi,

I'm using this middleware:

```
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secure" => true,
    "relaxed" => ["dev.example.com"],
    "path" => ["/app"],
    "passthrough" => [
        "/auth/token",
    ],
    "secret" => "secret_key",
    "callback" => function ($request, $response, $arguments) use ($container) {
	$container->logger->addInfo('JWT success');
        $container["jwt"] = $arguments["decode"];
    },
    "error" => function ($request, $response, $arguments) {
	$container->logger->addInfo('JWT error');
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
```

And when I send a request to e.g. "/auth/account", none of the callbacks are called. Also, error logs on apache are empty. It seems like the "/auth/account" is in passthrough list but it is not and actually, when I remove the "passthrough" section completely, I can send requests to "/auth/token" and it returns the correct response...

One more note, this code works fine on localhost but is not working on the production server.

What am I doing wrong?

Thanks in advance.

**Comment by tuupola** [comment]
> And when I send a request to e.g. "/auth/account", none of the callbacks are called. 

Callback is called only after successful authentication. You are only authenticating routes starting with `/app`. If you want to authenticate everything else than `/auth/token` change the `path` setting to `/`.

```php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => ["/"],
    "passthrough" => [
        "/auth/token",
    ],
    ...
]));
```
