### ISSUE TITLE
Error callback only accepts response interface

### ISSUE THREAD

**Issue by bilalds** [tuupola/slim-jwt-auth#165]
I have my JWTAuthentication middleware in a chain with other middlewares in slim. I want to continue to the next middleware even if JWTAuthentication fails but I am forces to send a response on fail. The error callback only accepts a Response interface so the api quits and returns at that point. 

It would be nice if I could continue down the chain of middleware and optionally return a 401 from the error callback in JWTAuthentication.

**Comment by tuupola** [comment]
I think you are looking for middleware which only parses the token but does not do authentication. You could use [firebase/php-jwt](https://github.com/firebase/php-jwt) and then save the token contents for later use. This middleware is only about authentication.

**Comment by bilalds** [comment]
@tuupola Okay, I guess that makes sense. I was using two different method of authentication and just wanted to see if I could chain them and check for both for that it would be nice to control the error callback. But I see what you're saying here.
