### ISSUE TITLE
[Question] How to ignore path with specific HTTP method?

### ISSUE THREAD

**Issue by samuelgfeller** [tuupola/slim-jwt-auth#179]
Let's say the path GET /posts is public and should work without token but the POST, PUT, DELETE /posts path should be authorised; how can I do that? 

Does it even make sense to want that?

**Comment by tuupola** [comment]
You could create a custom rule which is mixture of [RequestMethodRule](https://github.com/tuupola/slim-jwt-auth/blob/3.x/src/JwtAuthentication/RequestMethodRule.php) and [RequestPathRule](https://github.com/tuupola/slim-jwt-auth/blob/3.x/src/JwtAuthentication/RequestPathRule.php).

```php
$app = new Slim\App;
$app->add(new JwtAuthentication([
    "rules" => [
        new YourCustomRule([
            ...
        ])
    ]
]));
```

**Comment by samuelgfeller** [comment]
I will try to thank you
