### ISSUE TITLE
Slim v4. Always return 401.

### ISSUE THREAD

**Issue by mkraha** [tuupola/slim-jwt-auth#186]
How to get fixed.?? Please help

**Results:**
![image](https://user-images.githubusercontent.com/6831562/79671411-62409d00-81ca-11ea-9c0b-e484f6ef612f.png)

**Route:**
![image](https://user-images.githubusercontent.com/6831562/79671480-c3687080-81ca-11ea-9efb-fe2acc7deb9b.png)

**Settings.php:**
 `$settings['jwt'] = [ "path" => "/api", "secret" => $_ENV['JWT_SECRET'], ];`

**Container.php:**
```
JwtAuthentication::class => function (ContainerInterface $container) {
        $config = $container->get(Configuration::class)->getArray('jwt');

        $jwtMiddleware = new JwtAuthentication([
            "path" => $config['path'],
            "secret" => $config['secret']
        ]);

        return $jwtMiddleware;
    }
```

**Comment by tuupola** [comment]
In the `Authorization` header you are sending the secret key as the token. This is not correct. You are supposed to send a token signed with the secret key. 

https://github.com/tuupola/slim-jwt-auth#usage

**Comment by mkraha** [comment]
Oh yes. Cool its working 👍
