### ISSUE TITLE
Double Token in fetchToken

### ISSUE THREAD

**Issue by LudovicoPiccolo** [tuupola/slim-jwt-auth#187]
Hi,

via axios (react), I sent 2 requests:
1) I generate the token (www.example.com/token)
2) with the token I call the api (www.example.com/login?username=pippo&password=pluto)
this is debug:
      ["authorization"]=>
      object(Slim\Psr7\Header)#112 (3) {
        ["originalName":"Slim\Psr7\Header":private]=>
        string(13) "authorization"
        ["normalizedName":"Slim\Psr7\Header":private]=>
        string(13) "authorization"
        ["values":"Slim\Psr7\Header":private]=>
        array(2) {
          [0]=>
          string(363) "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODczMjM3MTAsImV4cCI6MTU4NzMyNDMxMCwianRpIjoiYUlneU80NkJlSW1MRmFNYWc1Ujh5Iiwic3ViIjoiY2xpZW50aWQiLCJ1c2VyX2FwaSI6IntcImFwaV9pZFwiOlwiMVwiLFwiYXBpX2NvZGVcIjpcIjJhMDg5YjA4OWNlNGE5Njk1MDRjMjQyYWI4OTQxZmU5MjgxMGJhM2NiYTViNTM1MjQwMmQzZGQ0NGYyNWQwYWZcIn0iLCJ1c2VyIjoiIn0.cD1uuifFCc_MsyT_kEyk-i64a8bSSP1tIsstKJW9tOs"
          [1]=>
          string(363) "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODczMjM3MTAsImV4cCI6MTU4NzMyNDMxMCwianRpIjoiYUlneU80NkJlSW1MRmFNYWc1Ujh5Iiwic3ViIjoiY2xpZW50aWQiLCJ1c2VyX2FwaSI6IntcImFwaV9pZFwiOlwiMVwiLFwiYXBpX2NvZGVcIjpcIjJhMDg5YjA4OWNlNGE5Njk1MDRjMjQyYWI4OTQxZmU5MjgxMGJhM2NiYTViNTM1MjQwMmQzZGQ0NGYyNWQwYWZcIn0iLCJ1c2VyIjoiIn0.cD1uuifFCc_MsyT_kEyk-i64a8bSSP1tIsstKJW9tOs"
        }
      }

So, in function fetchToken return two Bearer (token, Bearer token)
I solved it like this:

private function fetchToken(ServerRequestInterface $request): string
    {
        /* Check for token in header. */
        $header = $request->getHeaderLine($this->options["header"]);

        if (false === empty($header)) {
            if (preg_match($this->options["regexp"], $header, $matches)) {
                $this->log(LogLevel::DEBUG, "Using token from request header");
                $var=explode(",Bearer",$matches[1]);
                $matches[1]=$var[0];
                return $matches[1];
            }
        }

can you help me if i'm wrong to make calls?

**Comment by tuupola** [comment]
What is the purpose of sending two tokens? Usually you should sent just one.

**Comment by LudovicoPiccolo** [comment]
Look this code:

The var username and password are taken from the login form.

In the first axios, I take the token to see if the api user have access to the system.
then, with this token, I make calls for the various functions of the site...
in this case login, but I do the same for example to get the list of news




var session_url = 'https://api.example.com/V1/token';
  var clientid = 'clientid';
  var clientsecret = 'clientsecret';
  axios({
    method: 'post',
    auth: { username: clientid, password: clientsecret },
    url: session_url,
    headers: {
      "Content-Type": "application/json",
    }
  }).then((response) => {
    axios({
      method: 'post',
      url: "https://api.example.com/V1/login?username=" + username + "&password=" + password,
      headers: {
        "Authorization": "Bearer " + String(response.data.access_token),
      }
    }).then((response) => {
      alert("LOGGED");
    }).catch((error) => {
      alert("NOT LOGGED");
    })


  }).catch((error) => {
    alert("ERROR API ACCESS");
  })

**Comment by tuupola** [comment]
Something in your code sends two `Authorization` headers:

```
["values":"Slim\Psr7\Header":private]=>
array(2) {
   [0]=> string(363) "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODczMjM3MTAsImV4cCI6MTU4NzMyNDMxMCwianRpIjoiYUlneU80NkJlSW1MRmFNYWc1Ujh5Iiwic3ViIjoiY2xpZW50aWQiLCJ1c2VyX2FwaSI6IntcImFwaV9pZFwiOlwiMVwiLFwiYXBpX2NvZGVcIjpcIjJhMDg5YjA4OWNlNGE5Njk1MDRjMjQyYWI4OTQxZmU5MjgxMGJhM2NiYTViNTM1MjQwMmQzZGQ0NGYyNWQwYWZcIn0iLCJ1c2VyIjoiIn0.cD1uuifFCc_MsyT_kEyk-i64a8bSSP1tIsstKJW9tOs"
   [1]=> string(363) "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODczMjM3MTAsImV4cCI6MTU4NzMyNDMxMCwianRpIjoiYUlneU80NkJlSW1MRmFNYWc1Ujh5Iiwic3ViIjoiY2xpZW50aWQiLCJ1c2VyX2FwaSI6IntcImFwaV9pZFwiOlwiMVwiLFwiYXBpX2NvZGVcIjpcIjJhMDg5YjA4OWNlNGE5Njk1MDRjMjQyYWI4OTQxZmU5MjgxMGJhM2NiYTViNTM1MjQwMmQzZGQ0NGYyNWQwYWZcIn0iLCJ1c2VyIjoiIn0.cD1uuifFCc_MsyT_kEyk-i64a8bSSP1tIsstKJW9tOs"
}
```

Problem should go away if you send only one.

**Comment by tuupola** [comment]
No feedback, closing.
