### ISSUE TITLE
When I add jwt Middleware Its showing some error How to Solve this?

### ISSUE THREAD

**Issue by tonmooy** [tuupola/slim-jwt-auth#193]
When I add jwt Middleware Its showing some error in every routes, but ignore routes are working fine
@tuupola How to Solve this?

after update , my  composer v2

`$app->add(new Tuupola\Middleware\JwtAuthentication([
      "ignore"=>["/auth/login","/auth/register"],
        "secret"=>  "Token",
        "error"=>function ($response,$arguments)
        {
            $data["success"]= false;
            $data["response"]=$arguments["message"];
            $data["status_code"] = "401";

            return $response->withHeader("Content-type","application/json")
                ->getBody()->write(json_encode($data,JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
        }
    ]));
`

![Screenshot_1](https://user-images.githubusercontent.com/64668179/97173599-067b5000-17bb-11eb-978d-55d82708289f.png)

![Screenshot_2](https://user-images.githubusercontent.com/64668179/97174258-0891de80-17bc-11eb-9276-077c5cb5ec36.png)

**Comment by tuupola** [comment]
You are missing [psr/http-factory](https://packagist.org/packages/psr/http-factory) which is a dependency. I am not sure how that can happen since composer should install all the dependencies automatically.

**Comment by azrinaziz** [comment]
Have the same problem:

If installing `tuupola/*` packages:
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 5 installs, 0 updates, 1 removal
  - Removing psr/http-factory (1.0.1)
  - Locking neomerx/cors-psr7 (v1.0.13)
  - Locking tuupola/callable-handler (1.1.0)
  - Locking tuupola/cors-middleware (1.2.0)
  - Locking tuupola/http-factory (1.0.1)
  - Locking tuupola/slim-jwt-auth (3.5.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 5 installs, 0 updates, 1 removal
  - Removing psr/http-factory (1.0.1)
  - Installing tuupola/http-factory (1.0.1): Extracting archive
  - Installing tuupola/callable-handler (1.1.0): Extracting archive
  - Installing neomerx/cors-psr7 (v1.0.13): Extracting archive
  - Installing tuupola/cors-middleware (1.2.0): Extracting archive
  - Installing tuupola/slim-jwt-auth (3.5.0): Extracting archive
Generating autoload files
18 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

If I remove `tuupola/*` packages:
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 5 removals
  - Removing neomerx/cors-psr7 (v1.0.13)
  - Removing tuupola/callable-handler (1.1.0)
  - Removing tuupola/cors-middleware (1.2.0)
  - Removing tuupola/http-factory (1.0.1)
  - Removing tuupola/slim-jwt-auth (3.5.0)
  - Locking psr/http-factory (1.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 5 removals
  - Removing tuupola/slim-jwt-auth (3.5.0)
  - Removing tuupola/http-factory (1.0.1)
  - Removing tuupola/cors-middleware (1.2.0)
  - Removing tuupola/callable-handler (1.1.0)
  - Removing neomerx/cors-psr7 (v1.0.13)
  - Installing psr/http-factory (1.0.1): Extracting archive
Generating autoload files
15 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

`"psr/http-factory": "^1.0"` weirdly still exists in `composer.lock` file. Requiring `"psr/http-factory": "^1.0"` has no effect.

**Comment by azrinaziz** [comment]
**UPDATE**

If I revert my `composer` installation to v1:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 1 update, 0 removals
  - Installing psr/http-factory (1.0.1): Loading from cache
  - Updating tuupola/http-factory (1.0.1 => 1.3.0): Loading from cache
Writing lock file
Generating autoload files
19 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by juliansteenbakker** [comment]
I'm having the same issue as well: `Fatal error: Interface 'Psr\Http\Message\ResponseFactoryInterface' not found in /vendor/slim/psr7/src/Factory/ResponseFactory.php on line 18`

**Comment by tuupola** [comment]
@azrinaziz @juliansteenbakker What happens if you do `$ composer install tuupola/slim-jwt-auth`? What PHP version are you running? What is the output of `$ composer --version`?

**Comment by tuupola** [comment]
The problem is most likely that the old version of  `tuupola/http-factory` you are installing.

```
- Locking tuupola/http-factory (1.0.1)
```

It had a broken `provide` clause in `composer.json` which now seems to uninstall `psr/http-factory`. Should use atleast 1.0.2 or even better the latest which is 1.3.0.

https://github.com/tuupola/http-factory/blob/master/CHANGELOG.md#101---2018-12-19

**Comment by juliansteenbakker** [comment]
> The problem is most likely that the old version of `tuupola/http-factory` you are installing.

I didn't had http-factory present in my composer.json, but after adding http-factory:1.3.0 everything worked. Thanks for the work !

**Comment by tuupola** [comment]
Yeah, I don't really know why and old version was installed. It should automatically install the latest one.

**Comment by azrinaziz** [comment]
> 
> 
> @azrinaziz @juliansteenbakker What happens if you do `$ composer install tuupola/slim-jwt-auth`? What PHP version are you running? What is the output of `$ composer --version`?

Steps to reproduce:

1. Make sure `composer` is in `v1` and already update your dependencies using `composer update`.
2. Update `composer` to `v2` using `composer self-update --2`.
3. Run `composer update` again.

My `composer` version:
```
$ composer --version
Composer version 2.0.2 2020-10-25 23:03:59
```

`composer update` output after updating to `v2`:
```
$ composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 1 removal
  - Removing psr/http-factory (1.0.1)
  - Downgrading tuupola/http-factory (1.3.0 => 1.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 1 removal
  - Removing psr/http-factory (1.0.1)
  - Downgrading tuupola/http-factory (1.3.0 => 1.0.1): Extracting archive
Generating autoload files
18 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

My `php` version:
```
$ php -v
PHP 7.4.9 (cli) (built: Aug  4 2020 11:52:41) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Reverting `composer` to `v1` and running `composer update` again solves the problem.**

**Comment by tuupola** [comment]
@azrinaziz How does your composer.json look like. I try to understand why composer2 dowgrades `tuupola/http-factory` from 1.3.0 to 1.0.1. I cannot reproduce it myself.

**Comment by azrinaziz** [comment]
> 
> 
> @azrinaziz How does your composer.json look like. I try to understand why composer2 dowgrades `tuupola/http-factory` from 1.3.0 to 1.0.1. I cannot reproduce it myself.

```
{
    "name": "---redacted---",
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.2",
        "botman/botman": "^2.0",
        "botman/driver-web": "^1.0",
        "google/cloud-dialogflow": "^0.17",
        "php-di/php-di": "^6.0",
        "phpmailer/phpmailer": "^6.0",
        "slim/slim": "^4.0",
        "slim/psr7": "^1.0",
        "symfony/dotenv": "^5.0",
        "tuupola/cors-middleware": "^1.0",
        "tuupola/slim-jwt-auth": "^3.4",
        "vlucas/valitron": "^1.0"
    },
    "authors": [{
        "name": "Azrin Aziz",
        "email": "---redacted---"
    }],
    "autoload": {
        "psr-4": {
            "App\\Classes\\": "src/php/classes/",
            "App\\Controllers\\": "src/php/controllers/",
            "App\\Middleware\\": "src/php/middleware/",
            "App\\Models\\": "src/php/models/"
        }
    },
    "config": {
        "sort-packages": true
    }
}
```

**Comment by tuupola** [comment]
For some reason if `slim/psr7` is included composer2 will install old version of `tuupola/http-factory` (1.0.1).

```
{
    "require": {
        "slim/psr7": "^1.0",
        "tuupola/slim-jwt-auth": "^3.4"
    }
}
```

```
$ rm -rf vendor composer.lock && composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 11 installs, 0 updates, 0 removals
  - Locking fig/http-message-util (1.1.4)
  - Locking firebase/php-jwt (v5.2.0)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking slim/psr7 (1.2.0)
  - Locking tuupola/callable-handler (1.1.0)
  - Locking tuupola/http-factory (1.0.1)
  - Locking tuupola/slim-jwt-auth (3.5.0)
```

Without `slim/psr7` latest version of `tuupola/http-factory` (1.3.0) is installed.

```
{
    "require": {
        "tuupola/slim-jwt-auth": "^3.4"
    }
}
```

```
$ rm -rf vendor composer.lock && composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 9 installs, 0 updates, 0 removals
  - Locking firebase/php-jwt (v5.2.0)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking tuupola/callable-handler (1.1.0)
  - Locking tuupola/http-factory (1.3.0)
  - Locking tuupola/slim-jwt-auth (3.5.0)
```

All of this is most likely caused by the [incorrect provide clause](https://github.com/tuupola/http-factory/compare/1.0.0...1.0.1#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R35-R37) I had in 1.0.1.

I released a new version of `tuupola/slim-jwt-auth` which bumps the minimum requirement of `tuupola/http-factory` to 1.0.2.  This seems to fix the problem.

```
{
    "require": {
        "slim/psr7": "^1.0",
        "tuupola/slim-jwt-auth": "^3.5.1"
    }
}
```

```
$ composer --version
Composer version 2.0.2 2020-10-25 23:03:59

$ rm -rf vendor composer.lock && composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 12 installs, 0 updates, 0 removals
  - Locking fig/http-message-util (1.1.4)
  - Locking firebase/php-jwt (v5.2.0)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking slim/psr7 (1.2.0)
  - Locking tuupola/callable-handler (1.1.0)
  - Locking tuupola/http-factory (1.3.0)
  - Locking tuupola/slim-jwt-auth (3.5.1)
```

**Comment by azrinaziz** [comment]
> 
> 
> For some reason if `slim/psr7` is included composer2 will install old version of `tuupola/http-factory` (1.0.1).
> 
> ```
> {
>     "require": {
>         "slim/psr7": "^1.0",
>         "tuupola/slim-jwt-auth": "^3.4"
>     }
> }
> ```
> 
> ```
> $ rm -rf vendor composer.lock && composer update
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 11 installs, 0 updates, 0 removals
>   - Locking fig/http-message-util (1.1.4)
>   - Locking firebase/php-jwt (v5.2.0)
>   - Locking psr/http-message (1.0.1)
>   - Locking psr/http-server-handler (1.0.1)
>   - Locking psr/http-server-middleware (1.0.1)
>   - Locking psr/log (1.1.3)
>   - Locking ralouphie/getallheaders (3.0.3)
>   - Locking slim/psr7 (1.2.0)
>   - Locking tuupola/callable-handler (1.1.0)
>   - Locking tuupola/http-factory (1.0.1)
>   - Locking tuupola/slim-jwt-auth (3.5.0)
> ```
> 
> Without `slim/psr7` latest version of `tuupola/http-factory` (1.3.0) is installed.
> 
> ```
> {
>     "require": {
>         "tuupola/slim-jwt-auth": "^3.4"
>     }
> }
> ```
> 
> ```
> $ rm -rf vendor composer.lock && composer update
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 9 installs, 0 updates, 0 removals
>   - Locking firebase/php-jwt (v5.2.0)
>   - Locking psr/http-factory (1.0.1)
>   - Locking psr/http-message (1.0.1)
>   - Locking psr/http-server-handler (1.0.1)
>   - Locking psr/http-server-middleware (1.0.1)
>   - Locking psr/log (1.1.3)
>   - Locking tuupola/callable-handler (1.1.0)
>   - Locking tuupola/http-factory (1.3.0)
>   - Locking tuupola/slim-jwt-auth (3.5.0)
> ```
> 
> All of this is most likely caused by the [incorrect provide clause](https://github.com/tuupola/http-factory/compare/1.0.0...1.0.1#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R35-R37) I had in 1.0.1.
> 
> I released a new version of `tuupola/slim-jwt-auth` which bumps the minimum requirement of `tuupola/http-factory` to 1.0.2. This seems to fix the problem.
> 
> ```
> {
>     "require": {
>         "slim/psr7": "^1.0",
>         "tuupola/slim-jwt-auth": "^3.5.1"
>     }
> }
> ```
> 
> ```
> $ composer --version
> Composer version 2.0.2 2020-10-25 23:03:59
> 
> $ rm -rf vendor composer.lock && composer update
> Loading composer repositories with package information
> Updating dependencies
> Lock file operations: 12 installs, 0 updates, 0 removals
>   - Locking fig/http-message-util (1.1.4)
>   - Locking firebase/php-jwt (v5.2.0)
>   - Locking psr/http-factory (1.0.1)
>   - Locking psr/http-message (1.0.1)
>   - Locking psr/http-server-handler (1.0.1)
>   - Locking psr/http-server-middleware (1.0.1)
>   - Locking psr/log (1.1.3)
>   - Locking ralouphie/getallheaders (3.0.3)
>   - Locking slim/psr7 (1.2.0)
>   - Locking tuupola/callable-handler (1.1.0)
>   - Locking tuupola/http-factory (1.3.0)
>   - Locking tuupola/slim-jwt-auth (3.5.1)
> ```

I am happy to report that the problem has been fixed for `composer v2` user:
```
$ rm -rf vendor composer.lock && composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 54 installs, 0 updates, 0 removals
  - Locking botman/botman (2.6.1)
  - Locking botman/driver-web (1.5.1)
  - Locking evenement/evenement (v3.0.1)
  - Locking fig/http-message-util (1.1.4)
  - Locking firebase/php-jwt (v5.2.0)
  - Locking google/auth (v1.14.3)
  - Locking google/cloud-dialogflow (v0.17.2)
  - Locking google/common-protos (1.3)
  - Locking google/gax (1.5.0)
  - Locking google/grpc-gcp (0.1.5)
  - Locking google/protobuf (v3.13.0.1)
  - Locking grpc/grpc (1.30.0)
  - Locking guzzlehttp/guzzle (7.2.0)
  - Locking guzzlehttp/promises (1.4.0)
  - Locking guzzlehttp/psr7 (1.7.0)
  - Locking mpociot/pipeline (1.0.2)
  - Locking neomerx/cors-psr7 (v1.0.13)
  - Locking nikic/fast-route (v1.3.0)
  - Locking opis/closure (3.6.0)
  - Locking php-di/invoker (2.2.0)
  - Locking php-di/php-di (6.3.0)
  - Locking php-di/phpdoc-reader (2.2.1)
  - Locking phpmailer/phpmailer (v6.1.8)
  - Locking psr/cache (1.0.1)
  - Locking psr/container (1.0.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking react/cache (v1.1.0)
  - Locking react/dns (v1.4.0)
  - Locking react/event-loop (v1.1.1)
  - Locking react/promise (v2.8.0)
  - Locking react/promise-timer (v1.6.0)
  - Locking react/socket (v1.6.0)
  - Locking react/stream (v1.1.1)
  - Locking slim/psr7 (1.2.0)
  - Locking slim/slim (4.5.0)
  - Locking spatie/macroable (1.0.0)
  - Locking symfony/deprecation-contracts (v2.2.0)
  - Locking symfony/dotenv (v5.1.8)
  - Locking symfony/http-foundation (v5.1.8)
  - Locking symfony/polyfill-mbstring (v1.20.0)
  - Locking symfony/polyfill-php80 (v1.20.0)
  - Locking symfony/var-dumper (v5.1.8)
  - Locking tightenco/collect (v8.0.4)
  - Locking tuupola/callable-handler (1.1.0)
  - Locking tuupola/cors-middleware (1.2.0)
  - Locking tuupola/http-factory (1.3.0)
  - Locking tuupola/slim-jwt-auth (3.5.1)
  - Locking vlucas/valitron (v1.4.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 54 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php80 (v1.20.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.20.0): Extracting archive
  - Installing symfony/var-dumper (v5.1.8): Extracting archive
  - Installing tightenco/collect (v8.0.4): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/http-foundation (v5.1.8): Extracting archive
  - Installing spatie/macroable (1.0.0): Extracting archive
  - Installing react/event-loop (v1.1.1): Extracting archive
  - Installing evenement/evenement (v3.0.1): Extracting archive
  - Installing react/stream (v1.1.1): Extracting archive
  - Installing react/promise (v2.8.0): Extracting archive
  - Installing react/promise-timer (v1.6.0): Extracting archive
  - Installing react/cache (v1.1.0): Extracting archive
  - Installing react/dns (v1.4.0): Extracting archive
  - Installing react/socket (v1.6.0): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing opis/closure (3.6.0): Extracting archive
  - Installing mpociot/pipeline (1.0.2): Extracting archive
  - Installing botman/botman (2.6.1): Extracting archive
  - Installing botman/driver-web (1.5.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (1.7.0): Extracting archive
  - Installing guzzlehttp/promises (1.4.0): Extracting archive
  - Installing grpc/grpc (1.30.0): Extracting archive
  - Installing google/protobuf (v3.13.0.1): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.2.0): Extracting archive
  - Installing firebase/php-jwt (v5.2.0): Extracting archive
  - Installing google/auth (v1.14.3): Extracting archive
  - Installing google/grpc-gcp (0.1.5): Extracting archive
  - Installing google/common-protos (1.3): Extracting archive
  - Installing google/gax (1.5.0): Extracting archive
  - Installing google/cloud-dialogflow (v0.17.2): Extracting archive
  - Installing php-di/phpdoc-reader (2.2.1): Extracting archive
  - Installing php-di/invoker (2.2.0): Extracting archive
  - Installing php-di/php-di (6.3.0): Extracting archive
  - Installing phpmailer/phpmailer (v6.1.8): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing fig/http-message-util (1.1.4): Extracting archive
  - Installing slim/psr7 (1.2.0): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing psr/http-server-handler (1.0.1): Extracting archive
  - Installing psr/http-server-middleware (1.0.1): Extracting archive
  - Installing nikic/fast-route (v1.3.0): Extracting archive
  - Installing slim/slim (4.5.0): Extracting archive
  - Installing symfony/dotenv (v5.1.8): Extracting archive
  - Installing tuupola/http-factory (1.3.0): Extracting archive
  - Installing tuupola/callable-handler (1.1.0): Extracting archive
  - Installing neomerx/cors-psr7 (v1.0.13): Extracting archive
  - Installing tuupola/cors-middleware (1.2.0): Extracting archive
  - Installing tuupola/slim-jwt-auth (3.5.1): Extracting archive
  - Installing vlucas/valitron (v1.4.8): Extracting archive
16 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
19 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by tuupola** [comment]
Great. Thanks for the heads up to all who reported the bug. Thanks!

**Comment by tuupola** [comment]
For reference: https://github.com/composer/composer/issues/9316
