### ISSUE TITLE
Error Tuupola\Middleware\JwtAuthentication not found

### ISSUE THREAD

**Issue by eryucel** [tuupola/slim-jwt-auth#198]
I installed the middleware by "composer require tuupola/slim-jwt-auth" command. But I get "Fatal error: Uncaught Error: Class 'Tuupola\Middleware\JwtAuthentication' not found". I manually searched for it, but I could not find it either.

Vendor folder:
![resim](https://user-images.githubusercontent.com/33849527/100206489-71818900-2f17-11eb-934f-8e63af52d288.png)

composer.json :
![resim](https://user-images.githubusercontent.com/33849527/100206652-ab528f80-2f17-11eb-8bd3-f0e6dae85596.png)

**Comment by tuupola** [comment]
Run the following in you project folder find where files are installed.

```
$ find . -name JwtAuthentication.php
```

If the file is not found check the `composer install` output for any hints. As a sidenote the `composer.json` file looks unusual. The full version numbers should not be in the end of the lines.

**Comment by eryucel** [comment]
Couldn't find any files. 
It gives the same output every time I run the `composer install` command.
![resim](https://user-images.githubusercontent.com/33849527/100220146-fc6a7f80-2f27-11eb-8f6f-7c9d4a28e7f6.png)

I created a new empty project and tried `composer require tuupola/slim-jwt-auth` but again there is no `JwtAuthentication.php` file.

**Comment by tuupola** [comment]
Cannot reproduce.

```text
$ mkdir test
$ cd test 
$ composer require tuupola/slim-jwt-auth
Using version ^3.5 for tuupola/slim-jwt-auth
./composer.json has been created
Running composer update tuupola/slim-jwt-auth
Loading composer repositories with package information
Updating dependencies
Lock file operations: 9 installs, 0 updates, 0 removals
  - Locking firebase/php-jwt (v5.2.0)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking psr/http-server-handler (1.0.1)
  - Locking psr/http-server-middleware (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking tuupola/callable-handler (1.1.0)
  - Locking tuupola/http-factory (1.3.0)
  - Locking tuupola/slim-jwt-auth (3.5.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing psr/http-server-handler (1.0.1): Extracting archive
  - Installing tuupola/http-factory (1.3.0): Extracting archive
  - Installing psr/http-server-middleware (1.0.1): Extracting archive
  - Installing tuupola/callable-handler (1.1.0): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing firebase/php-jwt (v5.2.0): Extracting archive
  - Installing tuupola/slim-jwt-auth (3.5.1): Extracting archive
Generating autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
$ find . -name JwtAuthentication.php
./vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php
```

Maybe you have an empty file in cache. You could try clearing the composer cache before installing.

```
$ composer clearcache
```

If that does not help you could try doing a verbose install to look for hints.

```
$ composer require -vvv tuupola/slim-jwt-auth
```

**Comment by eryucel** [comment]
Thanks, following command solved the problem.
`$ composer clearcache`

**Comment by tuupola** [comment]
Great!
