### ISSUE TITLE
Return of Data

### ISSUE THREAD

**Issue by alfw** [tuupola/slim-jwt-auth#2]
Hello,

Im working with a restful api where i plan to use this lib in. But i have some challanges whiout hevey changes of your code. When you do your checks for the tokens and they are not valid, you just return the response code and no more data.

Is ther a way you cold add in support for return of data in the checks? Like a array input in the code with default data you want, then you can ether set a standar output message or allow it to be set when you open the Middleware?

**Comment by tuupola** [comment]
Can you show some pseudo PHP code which explains what you are trying to achieve.

**Comment by alfw** [comment]
Hello,

https://gist.github.com/alfw/f4216f14588c3f372ec1
https://gist.github.com/alfw/5a5f83d46320309c4b71

Changes i did on JwtAuthentication.php:
 - Line 34 : Added 'response' => null to the array
 - Line 90 to 93 : Added the response data i wanted. And also app render.
 - Line 100 to 103: Added the response data i wanted. And also app render.
 - Havent yet added the data to the false of callback.

Also to set the data from the new JwtAuthentication i had to add the 2 functiosn on line:
 - 433
 - 442

Reason for those changes is to be abel to print out json data for the restful api im working on.
Just return a 401 or 400 error status isent the best thing and we want more data on failded attemp.


I hope this explain it abit more.

**Comment by tuupola** [comment]
I did not mean to change any code of the plugin. I mean I do not fully understand the problem you currently have and wanted to see an example of what you currently cannot do with the plugin.

**Comment by tuupola** [comment]
In short you would like to be able to return some kind of response body with 40X response?

**Comment by alfw** [comment]
I want to return error data in the body, yeh.

**Comment by tuupola** [comment]
Last commit in master adds an optional error handler. It is called in cases like when decoding the token fails or token is not found. For example code below.

```php
$app->add(new JwtAuthentication([
    "secret" => "here be dragons...",
    "error" => function ($arguments) use ($app) {
        $response["status"] = "error";
        $response["message"] = $arguments["message"];
        $app->response->header("Content-Type", "application/json");
        $app->response->write(json_encode($response, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
```

If token is missing, it would output.

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json

{
    "status": "error",
    "message": "Token not found"
}
```

I am still playing around with this so things might change.

**Comment by alfw** [comment]
Tnx alot @tuupola , i work with this later tonight when im back at the project :)

**Comment by alfw** [comment]
Any plan to push this to composer?

**Comment by tuupola** [comment]
Already there. 

https://packagist.org/packages/tuupola/slim-jwt-auth

**Comment by tuupola** [comment]
Done.

https://packagist.org/packages/tuupola/slim-jwt-auth
