### ISSUE TITLE
Ignore path not working [SLIM 4][POSSIBLE BUG (?)]

### ISSUE THREAD

**Issue by samyan** [tuupola/slim-jwt-auth#200]
I'm trying to ignore the /auth path for login but it's not possible. What i'm doing bad?

**Route**
```
$app->group('/api/v1', function (Group $group) {
    $group->post('/auth', RouteCreator::create(['controller' => 'Auth', 'action' => 'login']));
    $group->get('/home', RouteCreator::create(['controller' => 'Home', 'action' => 'home']));
});
```

**JWT Config**
```
return new Tuupola\Middleware\JwtAuthentication([
        'secure' => false,
        'path' => '/',
        'ignore' => [
            '/api/v1/auth'
        ],
        'secret' => $jwtSettings['secret'],
        'error' => function ($response, $arguments) {
            $data = [
                'error' => true,
                'message' => $arguments['message']
            ];

            $response->getBody()->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));

            return $response
                      ->withHeader('Content-Type', 'application/json');
        }
    ]);

```

**Postman result:**

![image](https://user-images.githubusercontent.com/3801362/100556640-f667fc00-32a3-11eb-8def-dd4f7be697b4.png)

**Checking, i see if i put the absolute path, seems it works.**

**Like this:**
`/payment_system/web/backend/public/api/v1/auth`

**Comment by tuupola** [comment]
I am not sure which server or what kind of setup you are running, but it sounds like `$request->getUri()->getPath();` produces something unexpected. You could try debugging that by adding

```
var_dump($request->getUri()->getPath());
```

somewhere in your route.  Second thing you could try is to remove the route groups. I usually avoid them since they sometimes tend cause unexpected behaviour.

**Comment by samyan** [comment]
> I am not sure which server or what kind of setup you are running, but it sounds like `$request->getUri()->getPath();` produces something unexpected. You could try debugging that by adding
> 
> ```
> var_dump($request->getUri()->getPath());
> ```
> 
> somewhere in your route. Second thing you could try is to remove the route groups. I usually avoid them since they sometimes tend cause unexpected behaviour.

Hello,

`var_dump($request->getUri()->getPath());` gives: `/payment_system/web/backend/public/api/v1/currencies/prices`

I've tried without group routing but i get the same error. Trying the same with **tuupola/slim-jwt-auth:2.4** works fine, so the fail comes in **version 3.5**

**Comment by tuupola** [comment]
I see two problems. 

1) You are not requesting the `/api/v1/auth` path. Instead you are requesting `/api/v1/currencies/prices`.
2) Call to `$request->getUri()->getPath()` is returning the absolute path in filesystem `/payment_system/web/backend/public/api/v1/currencies/prices` when it should return the request path `/api/v1/currencies/prices`. The `$request` object is not created by this middleware, it is created by the Slim framework instead. Why it as the absolute path as request path I do not know. 

The code which checks the path for both versions is at:

https://github.com/tuupola/slim-jwt-auth/blob/3.5.0/src/JwtAuthentication/RequestPathRule.php
https://github.com/tuupola/slim-jwt-auth/blob/2.4.0/src/JwtAuthentication/RequestPathRule.php

**Comment by samyan** [comment]
> I see two problems.
> 
> 1. You are not requesting the `/api/v1/auth` path. Instead you are requesting `/api/v1/currencies/prices`.
> 2. Call to `$request->getUri()->getPath()` is returning the absolute path in filesystem `/payment_system/web/backend/public/api/v1/currencies/prices` when it should return the request path `/api/v1/currencies/prices`. The `$request` object is not created by this middleware, it is created by the Slim framework instead. Why it as the absolute path as request path I do not know.
> 
> The code which checks the path for both versions is at:
> 
> https://github.com/tuupola/slim-jwt-auth/blob/3.5.0/src/JwtAuthentication/RequestPathRule.php
> https://github.com/tuupola/slim-jwt-auth/blob/2.4.0/src/JwtAuthentication/RequestPathRule.php

`/api/v1/currencies/prices` It was an example. The same happenes with `/api/v1/auth` and with every route. I think the fail as you said, comes from **Slim V4**. I will check the base path parameter of framework.

Thank you.
