### ISSUE TITLE
Class 'Tuupola\Middleware\JwtAuthentication\RequestPathMethodRule' not found 

### ISSUE THREAD

**Issue by thomasFoglia** [tuupola/slim-jwt-auth#202]
Hi,

I was working with slim 3.1 until today.

I added `tuupola/cors-middleware`. Dependencies require upgrade from slim 3.1 to 3.5. Done.

since this installation, `Tuupola\Middleware\JwtAuthentication\RequestPathMethodRule` is no longer recognized.
I have this error : 
`Fatal error: Uncaught Error: Class 'Tuupola\Middleware\JwtAuthentication\RequestPathMethodRule' not found in...`

here is the code:
`
$app->add(new Tuupola\Middleware\JwtAuthentication([
    'rules' => [
        new Tuupola\Middleware\JwtAuthentication\RequestPathMethodRule([
            'passthrough' => [
                '/user' => ['POST'],
                  ...
            ]
        ]),
        new Tuupola\Middleware\JwtAuthentication\RequestPathRule([
            'path' => ['.......'],
            'ignore' => ['......']
        ]),
        new Tuupola\Middleware\JwtAuthentication\RequestMethodRule()
    ],
    'secret' => SALT_B,
    'algorithm' => ['HS256'],
    'error' => function ($response, $arguments) {
        $data['status'] = 'error';
        $data['message'] = $arguments['message'];
        return $response
            ->withHeader('Content-Type', 'application/json')
            ->getBody()->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
`

If I delete this part of code, no more error.
Why is RequestPathMethodRule not well called ?

My composer :
`
    "require": {
        "slim/slim": "^3.0",
        "tuupola/slim-jwt-auth": "^3.5",
        "tuupola/base62": "^0.11.1",
        "ext-curl": "^7.0",
        "ext-json": "^1.4",
        "zendframework/zend-diactoros": "^2.1",
        "tuupola/callable-handler": "^1.1",
        "tuupola/cors-middleware": "^1.2"
    }
`

Thanks you

**Comment by tuupola** [comment]
This middleware does not provide `RequestPathMethodRule` class. Instead there is `RequestMethodRule` and `RequestPathRule`.

https://github.com/tuupola/slim-jwt-auth/tree/3.x/src/JwtAuthentication

Maybe you had a custom self made rule in vendor which was removed when you updated the libraries?

**Comment by thomasFoglia** [comment]
Hi, that's exactly it, thank you very much
