### ISSUE TITLE
get attribute empty when using "ignore" endpoints

### ISSUE THREAD

**Issue by arthurl31** [tuupola/slim-jwt-auth#206]
I create the jwt auth config
```
function jwtAuth(): JwtAuthentication
{
    return new JwtAuthentication([
        'secure' => false,
        'ignore' => ['/token'],
        'secret' => env('JWT_SECRET')
    ]);
}
```

then in my controller if i try to:
`$request->getAttribute('token');`

It returns NULL, but if i remove the "ignore" from the JWT configuration it returns the decoded token just fine
```
    return new JwtAuthentication([
        'secure' => false,
        'secret' => env('JWT_SECRET')
    ]);

```

Does anyone knows what is happening?

**Comment by tuupola** [comment]
As the name implies the middleware is not executed in the ignored routes. Since the middleware was not executed it did not write the `token` attribute to the `$request` object.
