### ISSUE TITLE
Implementation for mobile?

### ISSUE THREAD

**Issue by VeeruPV** [tuupola/slim-jwt-auth#21]
Hey there guys,
Am wondering if a JWT can be implemented for REST calls from a mobile device. 

As of now, i can generate JWT tokens for browser based applications and it works pretty well. But I can't figure out how to do this for a mobile based application; any suggestions?

Thank you.

**Comment by tuupola** [comment]
There is not any difference in difference mobile application. Just generate the token and send it as `Authorization: Bearer` header when you make the REST call.
