### ISSUE TITLE
This works with public keys?

### ISSUE THREAD

**Issue by kosciuk** [tuupola/slim-jwt-auth#221]
Hi, I was using oauth server from https://oauth2.thephpleague.com/installation/ with public and private keys, but using the public key as secret with file_get_contents didn't work.

**Comment by tuupola** [comment]
Is it uses rsa256 then you should be able to use something like:

```php
$app = new Slim\App;

$app->add(new Tuupola\Middleware\JwtAuthentication([
    "secret" => $publickey
    "algorithm" => ["RS256"]
]));
```

You can find example of how to generate the token in [firebase/php-jwt](https://github.com/firebase/php-jwt#example-with-rs256-openssl) README. This middleware uses firebase/php-jwt for decoding the token.

**Comment by kosciuk** [comment]
It works! Thanks!

 But I think I will continue with the oauth server
