### ISSUE TITLE
How to add a leeway?

### ISSUE THREAD

**Issue by Dadinos** [tuupola/slim-jwt-auth#229]
Is it possible to set the leeway value during the initialisation ?

Something like:

```
app->add(new \Tuupola\Middleware\JwtAuthentication([
    "path" => ["/api"],
    "attribute" => "decoded_token_data",
    "secret" => $jwt,
    "algorithm" => ["HS256"],
    "leeway" => 50,          <- something like this possible??
    "before" => function ($response, $arguments) {
  } ....


Or is there another way to do it?

**Comment by tuupola** [comment]
There is no support for leeway. Personally I think leeway is a bad fix when server clock is wrong. It would be better to fix the server clock instead for example by using NTP. I never had a need to use leeway myself.

**Comment by Dadinos** [comment]
Ok make sense, thanks
