### ISSUE TITLE
[feature-request] Allow white-listing some HTTP methods on specific endpoints 

### ISSUE THREAD

**Issue by kirtangajjar** [tuupola/slim-jwt-auth#23]
As per my understanding, `RequestMethodRule` allows you to white-list methods globally, what if i want to white-list `GET` method on `/user`? I think this feature is not present and could be useful in various situations.

**Comment by tuupola** [comment]
People have different needs and it is impossible to cater everyones use cases. This is why I added the rule API to the plugin. You can create your own rules. Rule is just an callable. If the callable returns boolean false request will not be authenticated.

**Comment by kirtangajjar** [comment]
Cool, thanks!
