### ISSUE TITLE
Relaxed setting should also accept IP address

### ISSUE THREAD

**Issue by tnafele** [tuupola/slim-jwt-auth#239]
`'relaxed' => ['localhost', '10.10.10.15'],`

Calling from 10.10.10.15 throws 500 error. 
I guess this config parameter only accepts names? In development LAN there's often no DNS...

**Comment by tuupola** [comment]
Paste curl request and results here:

```
$ curl --include --ipv4 http://10.10.10.15
...
```

**Comment by tnafele** [comment]
@tuupola  Ahhh! I did misunderstand the option: I thought I have to add the IP/name of the clients for which SSL is not required (which would make more sense IMHO).

**Comment by tnafele** [comment]
To make my issue more clear: Maybe needs better description in the doc of how exactly the 'relaxes' property is treated.
I added the IP of the client from which I wanted to connect with plain text connection...

**Comment by tuupola** [comment]
Improved the wording on the security section: https://github.com/tuupola/slim-jwt-auth/pull/241
