### ISSUE TITLE
Callback function should be always triggered, even on passthrough routes

### ISSUE THREAD

**Issue by mateuslopes** [tuupola/slim-jwt-auth#27]
I think it would be very useful if callback function is always triggered, being a protected or passthrough route, having or not having a JWT to decode, so we can handle the situation according to the parameters we receive in this callback.

If there is a successful decoded token, it will come in the callback params, and if there is no token it will just not come. Then, we can make decision accordingly.

The problem with not triggering the callback function when on a passthrough route is that I lose the chance to set some useful variables and properties that would be important when a route is passed through.

**Comment by tuupola** [comment]
It is like this by design. Since middleware is about authentication, if a route is in passthrough list middleware quits early and does not do anything. It also does not assume token exists for routes which are not authenticated. 

It seems you just need to always decode the token and not do any actual authentication. You are already in correct path in your other bug report. For Slim 3 add a simple middleware which just always decodes the token and stores it somewhere. There is no need to tie it with this middleware. Both can coexist side by side. For Slim 2 you could use hooks for the same job.

**Comment by mateuslopes** [comment]
Hi @tuupola ,

Sorry for opening two similar issues. At my first glance, I thought they were different things, but now I see that this issue naturally becomes a consequence of the implementation of a policy to always decode the token, if the token is present with the proper Authorization header, even on passthrough routes.

I understand when you say:
<pre>It is like this by design. Since middleware is about authentication, if a route 
is in passthrough list middleware quits early and does not do anything. </pre>
At first, this looks like pretty reasonable and clear. If it is an authentication middleware, it should only be useful to authenticate if the route is closed and requires a token to access, otherwise, not useful.

But, that's not true! There are some situations which can be very useful to have the token decoded and ready to use, if we want to enhance the service for logged users, while serving a simpler version for public access.

Let's consider this example: I have an events application that serves in a API, all the shows and other cultural events that are happening around the current device position. There is a public route that serves the complete list of events to anyone, but restricted only to the basic descriptions of the event, but, if the user is already logged and passed a valid JWT token, then, the API will serve the events with the invitation list, and other restricted data.

So, i don't think that's the case when you said "It seems you just need to always decode the token and not do any actual authentication.", do you agree? Of course, authentication is not required, but, if it is there, I want use it.

Well, for now, of course I made an implementation that fixes these issues for my app, but I really think this might be an useful feature to have in this middleware.

Thanks ;)
