### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by Clowning** [tuupola/slim-jwt-auth#28]
Heu Tuupola, 

i want to implemente your library in my Slim Web API but i don't understand, how to return the token when i try to send a request for login (If the access are good ! )? 

Thanks :) ! (Sorry my english is not very good aha )

**Comment by tuupola** [comment]
Check [slim-api-skeleton](https://github.com/tuupola/slim-api-skeleton) for example implementation. Especially the part about [authentication and token](https://github.com/tuupola/slim-api-skeleton/blob/master/config/middleware.php#L32-L71).

**Comment by Clowning** [comment]
Hey Tuupola, thanks I managed to integrate the generation of a Token, but for test à create a simple route and when i call it via PostMan i have a Authorization header with my token for value but the server return an 401 error.. Do you have some idea?

**Comment by tuupola** [comment]
Either use the error callback to print out the error message.

```php
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
```

Or add an PSR-3 compatible logger and check from the log file.

**Comment by Clowning** [comment]
Oh good :) ! 

So my error is : 
```
"status": "error",
  "message": "Token not found"
```

When i make a request, what is the name of the attribute who have my token ? ["Token","Authorization",etc.. ?]

Thanks

**Comment by tuupola** [comment]
You should pass token as `Authorization: Bearer <token>` or a cookie named `token`. You can change the name of the cookie with parameter called `cookie`.

```php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => getenv("JWT_SECRET"),
    "cookie" => "foobar"
]));
```

**Comment by Clowning** [comment]
Oh right, thanks you ( Sorry it's my first time with Slim / JWT )

You have done a great job with you library, thanks a lot ! But i think it will a good thing to improve your documentation, for newbie like me it's very important aha ! 

Thanks a lot again :)
