### ISSUE TITLE
Using it with other psr7 stack then slim

### ISSUE THREAD

**Issue by lalop** [tuupola/slim-jwt-auth#30]
Hello,

I give a look to the Readme and it seems like we could use this library with other psr7 stack builder that match the same middleware signature then Slim.
Am I wrong ?

**Comment by tuupola** [comment]
Yes you should be able to use it with Relay et al. However I have not really tested it yet. There might be some Slim specific method accidentally used in the code. If you find any let me know.

**Comment by tuupola** [comment]
FYI. Just tested with a simple [ZF Expressive app](https://gist.github.com/tuupola/bb90a2311576e2f1573f8e927c78f86e) and seems to work ok.

**Comment by lalop** [comment]
This sounds really good, I added your project to my psr7 middleware list https://github.com/lalop/awesome-psr7
Thank you for the test
