### ISSUE TITLE
Insecure decode of JWT

### ISSUE THREAD

**Issue by masadelante** [tuupola/slim-jwt-auth#32]
In JWTAuthentication.php, Firebase\JWT is called in the following manner:

```
        return JWT::decode(
            $token,
            $this->options["secret"],
            ["HS256", "HS512", "HS384", "RS256"]
        );
```

Let's assume that a token has been signed with an RSA-256 private key, and that the corresponding public key is passed as a secret to the JWTAuthentication class. If an attacker were to craft a new JWT token containing { "alg": "HS256" } in the header and sign it with HMAC using the public key as a secret, this would result in the token being erroneously validated. Since public keys are, by their nature, meant to be transmitted, it isn't inconceivable that an attacker would be able to get hold of a public key.

Possible workarounds would be to add either a mandatory "algorithm" key to the options array, or even better to make it mandatory to provide a "kid" (key ID) in the header, since this allows the decoder to map a key ID to the corresponding algorithm.

**Comment by tuupola** [comment]
To better understand the problem you are describing can you provide code and/or token to reproduce the problem.  

If the problem you describe is `JWT::decode()` method would not the correct place to report it be the [firebase/php-jwt](https://github.com/firebase/php-jwt) library instead?

**Comment by tuupola** [comment]
Ignore previous. Quick Googling explained the problem.

**Comment by masadelante** [comment]
I'm happy to hear it, and let me congratulate you on a very useful piece of middleware for the Slim framework!
