### ISSUE TITLE
Unknown JSON error, but only on localhost

### ISSUE THREAD

**Issue by terrymun** [tuupola/slim-jwt-auth#33]
Thanks for the amazing plugin. I've managed to get it up and working with Slim v3 without any issue. The original implementation worked flawlessly, where I verify and decode a token in the `Authorization` header in the format of `Bearer: <token>`.

I am in the midst of adding another layer of Middleware, which will verify and decode an API access JSON web token. I have validated this JWT on jwt.io and it is properly formatted and can be successfully verified with a secret that I use. However, as the `Authorization` header is already used for a user token, the API JWT is provided via the `X-API-KEY` header, in the format of: `X-API-KEY: <token>`, sans the `Bearer` prefix.

For some reason, this JWT can be decoded successfully on my production server, but never on a development server hosted locally on localhost. I keep getting a `unknown JSON error: 5` in the `$arguments['message']` key. My implementation is as follow:

``` php
// Middleware for user token authentication
// This layer works all the time :) 
$api->add(new \Slim\Middleware\JwtAuthentication([
    'secret' => JWT_SECRET,
    'path' => ['/admin', '/users'],
    'secure' => true,
    'relaxed' => ['localhost'],
    'attribute' => 'user_auth_token',
    'error' => function($request, $response, $arguments) use ($c) {
        return $c['response']
            ->withStatus(401)
            ->withHeader('Content-Type', 'application/json')
            ->write(json_encode(array(
                'status' => 401,
                'message' => 'User authentication failed. '.$arguments['message']
                )));
    }
    ]));

// Middleware for API access token authentication
// This layers derps only when both Authorization and X-API-KEY headers are defined, and only on localhost
$api->add(new \Slim\Middleware\JwtAuthentication([
    'secret' => JWT_SECRET,
    'header' => 'X-API-KEY',
    'regexp' => '/(.*)/',
    'secure' => true,
    'relaxed' => ['localhost'],
    'attribute' => 'access_token',
    'error' => function($request, $response, $arguments) use ($c) {
        return $c['response']
            ->withStatus(401)
            ->withHeader('Content-Type', 'application/json')
            ->write(json_encode(array(
                'status' => 401,
                'message' => 'Access token verification failed. '.$arguments['message'],
                'token' => $request->getHeaders()['HTTP_X_API_KEY']
                )));
    }
    ]));
```

Interestingly, the `token` returned in the error callback is valid. So the `X-API-KEY` header is being correctly parsed and understood. Perhaps you might have an idea what is going wrong internally? I have tried installing Monolog, but the log file isn't showing up anywhere.

Some other tests:
1. Swapping the order of the middleware layer (whether user token or access token are verified in either order) does not make the error go away.
2. Removing the `Authorization` header (and the associated middleware layer) fixes the problem (i.e. having the `X-API-KEY` issued only, will cause the JSON error to go away). However, the error is localized to the middleware layer that verifies the `X-API-KEY` header, not the `Authorization` header.
3. Removing the `X-API-KEY` header (but _not_ the associated middleware layer) causes requests to passthrough. This should not happen.
4. Manually verifying the `X-API-KEY` header value in a custom middleware layer and using other libraries fixed the issue.

My hypothesis is that when both headers are used in conjuction, the JwtAuthentication middleware derps. However, I am unsure why this happens, nor can I explain it programatically.

**Comment by tuupola** [comment]
First question to come to mind is what is different between development server and production server? OS, PHP version etc?

**Comment by terrymun** [comment]
Thanks for the quick reply!

Both servers are running on identical versions of PHP (5.6), but the localhost is running off an AMPPS stack on OS X Yosemite while the production is running on CentOS7. Both servers have Apache configured to pass the Authorization header to PHP—I'm not sure if I have to do the same for the X-API-KEY header?

If you have any idea how I can pinpoint the source of the JSON error from within the middleware layer, I'll be very grateful :)

**Comment by tuupola** [comment]
The second one still tries to fetch the token from the default `HTTP_AUTHORIZATION`environment. You could try the changing it to `['HTTP_X_API_KEY']` or `null`.

``` php
$api->add(new \Slim\Middleware\JwtAuthentication([
    'secret' => JWT_SECRET,
    'environment' => ['HTTP_X_API_KEY'],
    'header' => 'X-API-KEY',
    'regexp' => '/(.*)/',
    'secure' => true,
    'relaxed' => ['localhost'],
    'attribute' => 'access_token',
    'error' => function($request, $response, $arguments) use ($c) {
        return $c['response']
            ->withStatus(401)
            ->withHeader('Content-Type', 'application/json')
            ->write(json_encode(array(
                'status' => 401,
                'message' => 'Access token verification failed. '.$arguments['message'],
                'token' => $request->getHeaders()['HTTP_X_API_KEY']
                )));
    }
    ]));
```

**Comment by terrymun** [comment]
@tuupola That fixed it! Thank you so much 👍 I have overlooked this statement in the readme:

> Note that usually, but not always there also is an HTTP_ environment which matches the header name.

Funny enough the HTTP_ environment is different on the development and production server. That's something new I've learned today.

**Comment by tuupola** [comment]
I need to document it better. Thanks for notifying!

**Comment by tuupola** [comment]
Oh, and using response from container is discouraged. It would be better to use the `$response` which is passed to error callback instead.

**Comment by terrymun** [comment]
Gotcha. I was probably referencing an outdated Middleware example on handling callbacks. Thanks for the catch!
