### ISSUE TITLE
Retry on JWT decoding failure.

### ISSUE THREAD

**Issue by rquast** [tuupola/slim-jwt-auth#34]
Firstly, thanks very much for this great project. It works very well!

I have an edge case where I am using openid connect to get the public key for the signature in jwks format (from from jwks_uri in /.well-known/openid-configuration) and I convert this key to PEM format so slim-jwt-auth can decode.

The problem I have is, if the keys are rotated on the provider, and I cache the converted PEM key to decode the token, I'd like to have slim-jwt-auth call some kind of retry callback on decode failure, so I can change the configuration to fetch the jwk again and convert it to a PEM and set it as the secret, then try to decode again. It currently sends a 401 not authorized on failure.

My current workaround is just to decode the token, and if that is okay, slim-jwt-auth will decode it again (adds overhead).

Is this a practical solution?

**Comment by tuupola** [comment]
This seems to be quite specific use case, but maybe you can do something in the [error callback](https://github.com/tuupola/slim-jwt-auth#error)?

**Comment by rquast** [comment]
Thanks for the tip. I'll see if I can do something with that.
