### ISSUE TITLE
No secure cookie usage?!

### ISSUE THREAD

**Issue by X-Tender** [tuupola/slim-jwt-auth#35]
Just curious, why do you use 
`$_COOKIE[$this->options["cookie"]]`
instead of
`$this->app->GetCookie($this->options["cookie"])`
this way it's possible to use encrypted cookies

**Comment by tuupola** [comment]
I honestly do not remember anymore. However `$app->getCookie()` is Slim 2 feature. Slim 3 version uses `$request->getCookieParams()`.

**Comment by X-Tender** [comment]
Yes I changed it that way. ☺️
