### ISSUE TITLE
Update firebase/php-jwt to latest? (4.0.0)

### ISSUE THREAD

**Issue by derpoho** [tuupola/slim-jwt-auth#37]
Might be an option, the changes don`t seems to reflect the version change in firebase/php-jwt ;)

**Comment by tuupola** [comment]
I did not even know there is new major version of `firebase/php-jwt`. Thanks for the heads up!

**Comment by derpoho** [comment]
i guess nobody noticed ;) i noticed it only because i wanted to add the lib to my project (i haven`t seen your dependency) and composer made noises ;)
