### ISSUE TITLE
Ability to set root path as passthrough

### ISSUE THREAD

**Issue by derpoho** [tuupola/slim-jwt-auth#38]
Hey,

maybe i am missing something, but it seems not to be possible to set the path to "/" and at the same time enable passthrough for "/", so that the root of the Url doen't have to be authenticated.

Am i right, or am i missing something?

Edit:
Forgot to mention WHY this isn't working. When both set to "/" all other routes are unauthenticated too. Although they are not set to passthrough.

**Comment by tuupola** [comment]
Setting `path` to `/`  means authenticate all routes. Another way to say this is authenticate all child routes of `/` including the `/`. Setting `passthrough` to `/`  means do not authenticate any routes.

If you for example want to only authenticate routes starting with `/api` do something like following:

``` php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/api", /* or ["/api", "/admin"] */
    "secret" => "supersecretkeyyoushouldnotcommittogithub"
]));
```

**Comment by derpoho** [comment]
So, it's not possible?

Scenario: I Want `/` and `/service` to pass through but any other route behind `/` like f.e. `/test` should be authenticated.

**Comment by tuupola** [comment]
You can either list all the folders ie. paths you want to authenticate in the `path` parameter. Or you can write your own rule class. It just needs to implement [RuleInterface](https://github.com/tuupola/slim-jwt-auth/blob/2.x/src/JwtAuthentication/RuleInterface.php) and return boolean `true` if you want to authenticate. Return boolean `false` if you do not want to authenticate. Use the stock [RequestPathRule](https://github.com/tuupola/slim-jwt-auth/blob/2.x/src/JwtAuthentication/RequestPathRule.php) as an example.

**Comment by derpoho** [comment]
ah, that makes sense!

Thanks
