### ISSUE TITLE
Set passthrough for each route

### ISSUE THREAD

**Issue by giolvani** [tuupola/slim-jwt-auth#39]
I am using slim 2, and I want allow the route straight from a middleware, something like this...

``` php
//public access
$app->get('/user/:id/public', new SomeMiddlewareToAuthorizeDirectAccess(), function ($id) use () {
    return ...
});

//private/auth access
$app->get('/user/:id', function ($id) use () {
    return ...
});
```

Or even a way to set path on passthrough with keys

``` php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "logger" => $logger,
    "secret" => "supersecretkeyyoushouldnotcommittogithub",
    "rules" => [
        new RequestPathRule([
            "path" => "/api",
            "passthrough" => ["/api/user/*/public"]
        ])
    ]
]));
```

It could be clear?
Thanks guys

**Comment by tuupola** [comment]
It is not possible to use regexp paths such as `/api/user/*/public`. However you can write your own rule. It just needs to implement [RuleInterface](https://github.com/tuupola/slim-jwt-auth/blob/1.x/src/JwtAuthentication/RuleInterface.php) and return boolean `true` if you want to authenticate. Return boolean `false` if you do not want to authenticate. Use the stock [RequestPathRule](https://github.com/tuupola/slim-jwt-auth/blob/1.x/src/JwtAuthentication/RequestPathRule.php) as an example.

**Comment by giolvani** [comment]
Hi, great!

And this custom rule, I could use as a middleware?

**Comment by tuupola** [comment]
You can use the custom rule in place of the default rules. Something like.

``` php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub",
    "rules" => [
        new YourCustomRule([
            "foo" => "bar"
        ])
    ]
]));
```

**Comment by giolvani** [comment]
Yeah, I was thinking set directly in the route, not in config.

like this:

``` php
$app->get('/user/:id/public', new SomeMiddlewareToAuthorizeDirectAccess(), function ($id) use () {
    return ...
});
```

Even I create my custom rule, I think because the flow, a route middleware, doesn't take effect.

Anyway, thank you very much for you attention.

;)

**Comment by giolvani** [comment]
Well, I solved this reorganizing my routes, this way I could put it on passthrough list.

Thanks in advance
