### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by giolvani** [tuupola/slim-jwt-auth#40]
Hey guys,

There any way to use refresh token with this lib?

If doesn't, how the best practice to implement that?

Sorry for my noob

**Comment by tuupola** [comment]
Middleware does not provide any ways to generate, issue or store authentication tokens. It only parses and authenticates a token when passed via header or cookie.

**Comment by giolvani** [comment]
Ow, my mistake!

I realize right now that is a middleware.

Thanks
