### ISSUE TITLE
Slim Error on redirecting from error callback

### ISSUE THREAD

**Issue by X-Tender** [tuupola/slim-jwt-auth#46]
I have a strange issue. Thats the error callback of the JWT JwtAuthentication (1.x).

``` javascript
"error" => function ($options) use ($app) {
        return $app->redirect( $app->urlFor('index') );
    }
```

On my development system (mamp php 5.6) the rediect from the "error" callback works fine.
On my productions erver (1&1 php 5.6) I get the following error:

```
Type: Slim\Exception\Stop
File: /SERVERPATH/htdocs/app/vendor_modules/slim/slim/Slim/Slim.php
Line: 1022
Trace

#0 /SERVERPATH/htdocs/app/vendor_modules/slim/slim/Slim/Slim.php(1042): Slim\Slim->stop()
#1 /SERVERPATH/htdocs/app/vendor_modules/slim/slim/Slim/Slim.php(1105): Slim\Slim->halt(302)
#2 /SERVERPATH/htdocs/app/php/start.php(151): Slim\Slim->redirect('/app/public/')
#3 /SERVERPATH/htdocs/app/vendor_modules/tuupola/slim-jwt-auth/src/JwtAuthentication.php(150): {closure}(Array)
#4 /SERVERPATH/htdocs/app/vendor_modules/tuupola/slim-jwt-auth/src/JwtAuthentication.php(97): Slim\Middleware\JwtAuthentication->error(Array)
#5 /SERVERPATH/htdocs/app/vendor_modules/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\JwtAuthentication->call()
#6 /SERVERPATH/htdocs/app/vendor_modules/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#7 /SERVERPATH/htdocs/app/php/start.php(176): Slim\Slim->run()
#8 /SERVERPATH/htdocs/app/public/index.php(2): require('/SERVERPATH/d...')
#9 {main}
```

What could be wrong?!

**Comment by tuupola** [comment]
Slim 2 uses exceptions internally for control flow. You are seeing one of these Slim 2 control flow exceptions. Look for differences in your development and production config.

**Comment by X-Tender** [comment]
Honestly thats not realy any difference except the DB Connect credentials.
So I sould better bother the slim developer about the issue :) ?!

**Comment by tuupola** [comment]
It is Slim which throws the exception, not the middleware.

https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1102-L1105
https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1037-L1043
https://github.com/slimphp/Slim/blob/2.x/Slim/Slim.php#L1020-L1023

Why the Exception is ignored on development host and shown on live host I do not know. However quick Google search reveals this.

http://stackoverflow.com/questions/25902650/slim-redirect-works-but-also-throws-an-exception

**Comment by X-Tender** [comment]
Thanks. I packed it now that way and it works :/ But it feels wrong.

``` php
try {
    return $app->redirect( $app->urlFor('index') );
} catch(\Exception $e) {}
```

**Comment by tuupola** [comment]
Yeah I agree. I think that was the reason those Exceptions were dropped in 3.x.
