### ISSUE TITLE
How to add it without composer?

### ISSUE THREAD

**Issue by mgsotelo** [tuupola/slim-jwt-auth#5]
I have a working Slim app (added without composer), and now I want to implement slim-jwt-auth but i can't figure it out how to do it (autoloading, i think) 

Is there any option to do this?
If so, what are the steps that I need to follow in order to achieve the integration of Slim and Slim-jwt-auth.

Any help would be very appreciated :+1:

**Comment by tuupola** [comment]
Composer is pretty much the de facto standard these days so you really would be better of installing via composer. It might be possible to do a git clone and include files from the src folder. That is unsupported though.
