### ISSUE TITLE
404 error on request

### ISSUE THREAD

**Issue by crimsonmoin** [tuupola/slim-jwt-auth#51]
Hi, 
i get a 404 error when i make a get request to the api when using with angular 2, at first i felt it was problem with angular 2 service. But when i tested with other api's it works, but gives 404 error with a response saying 
{message: "Not found"}
Its an issue on the api side what am i doing wrong, is it the cors issue, Please help

**Comment by tuupola** [comment]
Can you  minimal code which reproduces the error together witch example curl request including the headers.

**Comment by crimsonmoin** [comment]
i have just cross checked on it, on investigation what i have found it the browser is sending a pre flight request due to which the requests are failing. I have seen that your template already has cors enabled even than the preflight issue pops up. Any suggestions to get around it.

**Comment by crimsonmoin** [comment]
i found a solution stating to add headers
$app->response()->headers->set('Access-Control-Allow-Headers', 'Content-Type,Accept');
    $app->response()->headers->set('Content-Type', 'application/json');
    $app->response()->headers->set('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    $app->response()->headers->set('Access-Control-Allow-Origin', '*');

when i add this headers the preflight response is handled but slim throws an exception
Uncaught BadMethodCallException: Method response is not a valid method

**Comment by tuupola** [comment]
This is not related to JWT middleware. As you said browser is doing a preflight request. If you are using some PSR-7 based framework as Slim 3 you could use a [CORS middleware](https://github.com/tuupola/cors-middleware).

**Comment by crimsonmoin** [comment]
isnt your jwt skeleton already cors enabled with cors middleware enabled ?? or do i need to add to it explicitly.

**Comment by tuupola** [comment]
Yes it has the [CORS middleware enabled](https://github.com/tuupola/slim-api-skeleton/blob/master/config/middleware.php#L59-L76).

**Comment by crimsonmoin** [comment]
Yes, even with all the middlewares enabled still when i make a request it throws the preflight issue. If i append headers again the preflight issue vanishes, but the routes start throwing an error stating message : not found. In postman when i test it works perfectly though.

**Comment by tuupola** [comment]
Like I said I need to see the failing request as curl example. 

Also now when I read your previous comment I do not know what is the **JWT skeleton** you are referring to?  If you mean the [Slim API Skeleton](https://github.com/tuupola/slim-api-skeleton) here is how it responds to a preflight request.

```php
$ curl "http://192.168.50.52/todos" --request OPTIONS --include --header "Access-Control-Request-Method: PUT" --header "Origin: http://www.example.com"
HTTP/1.1 200 OK
Date: Wed, 01 Mar 2017 15:19:52 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.28
Access-Control-Allow-Origin: http://www.example.com
Access-Control-Allow-Credentials: true
Vary: Origin
Access-Control-Max-Age: 60
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8
```

**Comment by tuupola** [comment]
No feedback.

**Comment by rdpascua** [comment]
I'm having the same issue, when throwing an error, the middleware doesn't use cors middleware `\Tuupola\Middlware\Cors` this is common when using js framework.

I suggest that @crimsonmoin re-order the middleware. It is common that your CORS middleware fires first before the JWTMiddleware

**Comment by tuupola** [comment]
@rdpascua It is an framework issue. When you throw an exception it stops executing middleware stack and goes straight to the error handler.

**Comment by rdpascua** [comment]
@tuupola actually moving the middleware stack works. The order seems important when using slim middleware, as a matter of fact this is very similar on how lumen/laravel middleware works out of the box. We should put a disclaimer on your readme when someone uses your cors middleware that ordering is important. don't you think?
