### ISSUE TITLE
Critical vulnerabilities in JSON Web Token libraries - Covered?

### ISSUE THREAD

**Issue by derpoho** [tuupola/slim-jwt-auth#55]
Since i have your implementation in many webapps... is this vulnerability covered?

https://www.chosenplaintext.ca/2015/03/31/jwt-algorithm-confusion.html

Greets Marcus

**Comment by derpoho** [comment]
Just seen that it was March 2015...  I guess it is covered already. Please close if it has no relevance.

Edit: More research shows 2017 too: http://blog.intothesymmetry.com/2017/03/critical-vulnerability-in-json-web.html

**Comment by tuupola** [comment]
Yes. See https://github.com/tuupola/slim-jwt-auth/commit/69ab6a25bbb0c22c941fd319cc53bc3eacda9df5 which fixes the problem.

**Comment by derpoho** [comment]
Nice! Thanks for the fast reply (again) ;)
