### ISSUE TITLE
Google jwt authentication

### ISSUE THREAD

**Issue by manelj** [tuupola/slim-jwt-auth#56]
Did anyone extended the JwtAuthentication class to work as a GoogleJwtAuthentication ?
I mean, i have an android app that gets Google token, then i want to send it to my API (slim) server to get my own jwt token from api.

**Comment by tuupola** [comment]
How would the `GoogleJwtAuthentication` class be different?

**Comment by manelj** [comment]
I'm creating an android app with google sign-in, and then use my own API php (slim)
In this guides Google suggest that the token get from google has to be verified
https://developers.google.com/identity/sign-in/android/backend-auth

Something like:

```
require_once 'vendor/autoload.php';

// Get $id_token via HTTPS POST.

$client = new Google_Client(['client_id' => $CLIENT_ID]);
$payload = $client->verifyIdToken($id_token);
if ($payload) {
  $userid = $payload['sub'];
  // If request specified a G Suite domain:
  //$domain = $payload['hd'];
} else {
  // Invalid ID token
}
```

**Comment by tuupola** [comment]
Sorry I still do not understand the request. What is the problem you have at the moment or is there a feature you are missing?

**Comment by manelj** [comment]
I'm trying this approach.
Android app, does Google sign in.
Android app, get Google token
Android app, post this token to API (slim) to get a native API jwt (with scopes, etc...)
In this third step, do you think that google token received by php api must be checked/verified against google servers? or it's enougth the slim-jwt-auth verifications/validations of received jwt?

**Comment by tuupola** [comment]
Whether you verify something against Google servers  depends on the application you are building. 

The middleware just validates whether the given token is valid or not. If you need some additional authentication logic you could use the [callback](https://github.com/tuupola/slim-jwt-auth#callback) parameter for this.

That said if you trust the token I do not see any reason why you revalidate it after it has already been validated. Unless of course there is some other logic in the application itself which needs this.
