### ISSUE TITLE
JWT Apache PHP 7 Remote

### ISSUE THREAD

**Issue by elvispdosreis** [tuupola/slim-jwt-auth#57]
I'm having a problem with JWT, but I do not know how to explain it correctly.

With the local php server built in it works fine, however when I upload to production using a remote apache server I can not use the token, all the pages I send from the 401.
But I can log in to the remote server and use the token on the local server

```
<?php
$app->add(new \Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware);

$app->add(new \Slim\HttpCache\Cache('public', 86400));
$app->add(new App\Middleware\CorsMiddleware());
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => "4lwobXXXXXXXXXXXXXdDt",
    "secure" => true,
    "relaxed" => [
        "localhost"
    ],
    "callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    },
    "rules" => [
        new Slim\Middleware\JwtAuthentication\RequestPathRule([
            "path" => "/",
            "passthrough" => [
                "/auth/login"
            ]
        ]),
        new \Slim\Middleware\JwtAuthentication\RequestMethodRule([
            "passthrough" => ["OPTIONS"]
        ])
    ]
]));
```

**Comment by tuupola** [comment]
You can add a [logger](https://github.com/tuupola/slim-jwt-auth#logger) and see from log file why authentication fails. Alternatively you can setup an [error callback](https://github.com/tuupola/slim-jwt-auth#error) which spits out the reason for failure.
