### ISSUE TITLE
Token not found

### ISSUE THREAD

**Issue by 4slimbu** [tuupola/slim-jwt-auth#58]
I have used slim-jwt-auth in my api. It works fine on localhost and on testing server but on production vps server, it shows token not found.
Htaccess for the VPS server is modified to support Http:authorization
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
    Header set Access-Control-Allow-Headers "Content-Type, Authorization"
</IfModule>

Am I missing something?

**Comment by tuupola** [comment]
Quickly looking everything looks ok. First I would test by doing the request using curl to make sure you are actually sending the token. Do not use Postman or anything similar, with curl you can be sure what kind of  request is made.

```php
$ curl "https://example.com/foos" \
    --request GET \
    --include \
    --insecure \
    --header "Authorization: Bearer $TOKEN" 
```

If token is really sent I would then start to debug why live server does not see it: `print_r(apache_request_headers())`, `print_r($_SERVER)` etc.

**Comment by 4slimbu** [comment]
I tried 
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
instead of 
RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
and it is working now.

Thanks
