### ISSUE TITLE
php-jwt 5.0.0 stable not supported yet

### ISSUE THREAD

**Issue by MartinP7r** [tuupola/slim-jwt-auth#59]
`tuupola/slim-jwt-auth 2.3.2 requires firebase/php-jwt ^3.0 || ^4.0 -> satisfiable by firebase/php-jwt[v3.0.0, v4.0.0] but these conflict with your requirements or minimum-stability.`

latest stable is 5.0.0 https://github.com/firebase/php-jwt 
could you update your dependency settings for ^5.0?

**Comment by BafS** [comment]
This issue resolved in the last version https://github.com/tuupola/slim-jwt-auth/pull/61

**Comment by MartinP7r** [comment]
thanks, i'll check that out today!
