### ISSUE TITLE
Syntax Error and 'use' missing

### ISSUE THREAD

**Issue by JorgeCLN** [tuupola/slim-jwt-auth#6]
Hi, in the part of rules is missing one "]" for close $app->add(new \Slim\Middleware\JwtAuthentication([ and also is missing "use \Slim\Middleware\JwtAuthentication\RequestMethodRule; use \Slim\Middleware\JwtAuthentication\RequestPathRule;" if not show an error of class

Greets

**Comment by tuupola** [comment]
Fixed. Thanks for the heads up!
