### ISSUE TITLE
exception "Key may not be empty" though key is found

### ISSUE THREAD

**Issue by MartinP7r** [tuupola/slim-jwt-auth#60]
I'm trying to authenticate the token in my Authorization header. Everything seems to be set correctly and the token seems to be recognized as being passed to the middleware (logger says: `Using token from environment`)  
![image](https://user-images.githubusercontent.com/2669027/27850668-1a6942ea-6191-11e7-9b74-e26361c1869e.png)

my current middleware object:
```php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secure" => false,
    "secret" => getenv("JWT_SECRET"),
    "path" => "/",
    "passthrough" => ["/auth"],
    "algorithm" => ["HS256"],
    "logger" => $container['logger']
]));
```
token is being encoded as:
```php
$jwt = JWT::encode($token, getenv("JWT_SECRET"), 'HS256');
```
logging with monolog.  
if googled and searched on stackoverflow but couldn't find more information on this particular error message. Could anybody tell me what I'm doing wrong?

**Comment by tuupola** [comment]
How does the token look like? Does it validate on https://jwt.io/ ?

**Comment by MartinP7r** [comment]
found the problem. my secret was actually empty at the time it tried to read the environment variable. when testing directly with php-jwt it was already loaded, that's what confused me.  
sorry to waste your time!

**Comment by Ediannys** [comment]
Graciaaaas, me paso a mi también, tenia como 1 hora buscando el error!

**Comment by stefhodes** [comment]
Hi @MartinP7r 

How to solve this issue I face the same issue.

**Comment by Hothi-Jimit** [comment]
Hi @MartinP7r 

How to solve this issue i face same issue.

**Comment by MartinP7r** [comment]
@jaimin-hothi make sure your `secret` value is actually set in time. 
Can't really say if that is relevant for your case, though.
