### ISSUE TITLE
Insecure use of middleware over HTTP denied by configuration

### ISSUE THREAD

**Issue by ganesh35** [tuupola/slim-jwt-auth#62]
Please help:
My code is as follows:
```php
$container["JwtAuthentication"] = function ($container) {
    return new JwtAuthentication([
        "path" => "/",
        "passthrough" => ["/token", "/info"],
        "secret" => getenv("JWT_SECRET"),
        "logger" => $container["logger"],
        "secure" => false,   // Only https
        "error" => function ($request, $response, $arguments) {
            $data["status"] = "error";
            $data["message"] = $arguments["message"];
            return $response
                ->withHeader("Content-Type", "application/json");
        },
        "callback" => function ($request, $response, $arguments) use ($container) {
            $container["token"]->hydrate($arguments["decoded"]);
        }
    ]);
};
```

I already set "secure" to false,  byt still not working.

curl -X POST \
  http://api.example.com/token \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{"username":"someuser","password":"somepassword"}'

500 Internal Server error
```json
{
    "status": "error",
    "message": "Insecure use of middleware over HTTP denied by configuration."
}
```
BTW: it is working good on localhost

**Comment by tuupola** [comment]
In your config the `/token` path is not authenticated by JWT middleware. 

```
 "passthrough" => ["/token", "/info"],
```

If you are using [Basic Auth middleware](https://github.com/tuupola/slim-basic-auth)  for authenticating the '/token'  path set `"secure" => false` there too.  Note that this is a security risk and should not be used in live environment.
