### ISSUE TITLE
Environment variable ans secrets 

### ISSUE THREAD

**Issue by sinzen** [tuupola/slim-jwt-auth#63]
Hi,

I have one question about the secrets variable..
Is the secret variable still hard coded in the application ? I can't do it randomly ?

Where I store this secret variable ?

Thanks

**Comment by tuupola** [comment]
You use the secret key to authenticate the token, ie. to make sure it has not been tampered with. To authenticate you must use the same key for both generating and authenticating.

You can of course generate a random key, but you still have to store it somewhere. You can store the key in the same way as you would store a password. In other words you should not commit it to GitHub. One good candidate is to store them in environment. You could of course store them in an external config file too.
