### ISSUE TITLE
How we can Invalidate or Blacklist token when user logout

### ISSUE THREAD

**Issue by anehkumar** [tuupola/slim-jwt-auth#67]
Hi @tuupola , thanks for your library, I am using your library (slim-jwt-auth) it is very useful but I don't know how to invalidate token or add a token to the blacklist when the user logout.

**Comment by tuupola** [comment]
You could for example save the invalidated token to database. Check for the token in the callback and return boolean `false` if blacklisted. Something like:

```php
$app->add(new \Slim\Middleware\HttpBasicAuthentication([
    "path" => "/admin",
    "users" => [
        "root" => "t00r",
        "somebody" => "passw0rd"
    ],
    "callback" => function ($request, $response, $arguments) {
        $token = $request->getAttribute("token");
        if (check whether $token is blacklisted here) {
            return false;
        }
    }
]));
```

Bad thing is now your API is not stateless anymore since you have query database with every request.
