### ISSUE TITLE
Passtrhough on route + method

### ISSUE THREAD

**Issue by patforg** [tuupola/slim-jwt-auth#68]
I would like to let some routes passthrough based on the method.

For example  I have two routes:
1. POST /user
2. GET /user

The POST route is to create a new user  and should passthrough
The GET route is to get the current user and should validate the token

Not sure that it's possible to accomplish this with the current rules.

Thanks

**Comment by tuupola** [comment]
Not possible with current rules but you can always create your own rule. Rule must implement a [RuleInterface](https://github.com/tuupola/slim-jwt-auth/blob/2.x/src/JwtAuthentication/RuleInterface.php) ie. it should be callable. If any of the rules returns boolean `false` the request will not be authenticated.

```php
$app = new \Slim\App();

$app->add(new \Slim\Middleware\HttpBasicAuthentication([
    "rules" => [
        new \Slim\Middleware\HttpBasicAuthentication\RequestPathRule([
            "path" => "/",
            "passthrough" => ["/public"]
        ]),
        new \Some\CustomRule([
            "foo" => "bar"
        ])
    ]
]));
```

**Comment by patforg** [comment]
Thanks for the reply.  I've started working on creating a custom rule class.
The "passthrough" option will have paths as keys and an array of accepted methods as values.

```php
new \Some\CustomRule([
  "passthrough" => [
    "/user" => [ "POST", "GET",  ],
    "/session" => [ "POST" ]
  ],
]);
```


Would you be interested in a pull request if it is similar the current rule classes?

**Comment by tuupola** [comment]
Since it is not a common case and it would be one more thing to support I would rather not include it in main repository. However I would be happy to link it from the README if you make a separate repository or a gist.

**Comment by legoguy1000** [comment]
@patforg Did you ever make a repo for your rule?  I am looking at the same scenario and if you already have made it, it would save me time.

**Comment by PhouvanhKCSV** [comment]
@patforg Could you please show me how is your custom rule ?

**Comment by legoguy1000** [comment]
@patforg I actually created a rule to do this.

```
public function __invoke(ServerRequestInterface $request): bool
    {
        $uri = "/" . $request->getUri()->getPath();
        $uri = preg_replace("#/+#", "/", $uri);
        /* If request path is matches ignore should not authenticate. */
        foreach ((array)$this->options["passthrough"] as $path=>$methods) {
            $ignore = rtrim($path, "/");
            if (!!preg_match("@^{$ignore}$@", $uri) && in_array($request->getMethod(),$methods)) {
                return false;
            }
        }
        return true;
    }
new Tuupola\Middleware\JwtAuthentication\RequestPathMethodRule([
          "passthrough" => [
            "/asdf/([a-z0-9]{13})" => ["GET"],
            "/asdf/([a-z0-9]{13})/asdf" => ["GET"],
          ],
        ])
```
