### ISSUE TITLE
Not working with Slim 3

### ISSUE THREAD

**Issue by ronaldo-systemar** [tuupola/slim-jwt-auth#7]
- tuupola/slim-jwt-auth 0.3.0 requires slim/slim ~2.3 -> satisfiable by slim/slim[2.x-dev].
    - tuupola/slim-jwt-auth 0.3.0 requires slim/slim ~2.3 -> satisfiable by slim/slim[2.x-dev].
    - tuupola/slim-jwt-auth 0.3.0 requires slim/slim ~2.3 -> satisfiable by slim/slim[2.x-dev].
    - Can only install one of: slim/slim[3.x-dev, 2.x-dev].
    - Installation request for slim/slim 3.x-dev -> satisfiable by slim/slim[3.x-dev].
    - Installation request for tuupola/slim-jwt-auth ^0.3.0 -> satisfiable by tuupola/slim-jwt-auth[0.3.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by tuupola** [comment]
Apparently something has changed. Composer does not know how to choose correct version for Slim 3 at the moment. You can manually install the correct version for Slim 3 with.

```php
$ composer require tuupola/slim-jwt-auth:~2.0@dev
```

**Comment by ronaldo-systemar** [comment]
Thank you tuupola, it works for now.
