### ISSUE TITLE
$arguments["decoded"] is not array why?

### ISSUE THREAD

**Issue by khusanov** [tuupola/slim-jwt-auth#70]
{
    "title": "Token not allowed to get a user",
    "type": "about:blank",
    "status": 403
}<br />
<b>Notice</b>:  Trying to get property of non-object in <b>/Users/username/../ProjectName/src/App/Token.php</b> on line <b>15</b><br />
<br />
<b>Warning</b>:  array_intersect(): Argument #2 is not an array in <b>/Users/username/../ProjectName/src/App/Token.php</b> on line <b>15</b><br />

**Comment by tuupola** [comment]
No idea. You could try to  debug the token at https://jwt.io/

**Comment by khusanov** [comment]
token is valid. my token like this 
```
{
  "iat": 1505893996,
  "exp": 1505901196,
  "jti": "1zQgWioFFUQi3qd3reuTEV",
  "sub": "root",
  "scope": [
    "user.get"
  ]
}
```

**Comment by tuupola** [comment]
I would sprinkle `print_r()` calls to strategic places in the code to see the contents of received decoded token and if correct token is received, where it loses the values.

**Comment by khusanov** [comment]
```
"before" => function ($request, $response, $arguments) use ($container) {
            $container["token"]->hydrate($arguments["decoded"]);
 }
```
$arguments["decoded"] is null

**Comment by khusanov** [comment]
before doesn't work

**Comment by khusanov** [comment]
I changed before to callback

**Comment by tuupola** [comment]
What version are you using? 2.x has `callback` but not `before`. 3.x has `before` but not `callback`.  There is no version which has both.
