### ISSUE TITLE
Passthrough not checking secure

### ISSUE THREAD

**Issue by tharyanto** [tuupola/slim-jwt-auth#72]
```
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secure" => true,
    "relaxed" => ["localhost", "dev.example.com"],
    "path" => ["/api", "/admin"],
    "passthrough" => ["/api/token", "/admin/ping"],
    "secret" => "supersecretkeyyoushouldnotcommittogithub"
]));
```

shouldn't http://www.example.com/api/token failed because it's insecure?

**Comment by tuupola** [comment]
No, plugin is totally ignored in the `passthrough` routes. This includes the `secure` setting. If you are using [slim-basic-auth](https://github.com/tuupola/slim-basic-auth/) for the `/api/token` route you could force https there.

If you want to force https on the whole site, you could do that with either `mod_rewrite` or a [force https middleware](https://github.com/oscarotero/psr7-middlewares#https).
