### ISSUE TITLE
fetchToken() returns false even if  header is found

### ISSUE THREAD

**Issue by D4rkMindz** [tuupola/slim-jwt-auth#79]
I am using current Middleware setup:
```
$app->add(new JwtAuthentication([
        'header' => 'X-Token',
        'secret' => $secret,
        'passthrough' => $passthrough, // array with routes ['/', '/auth'] etc...
        'callback' => function (Request $request, Response $response, array $arguments) use ($container) {
            $container['jwt'] = $arguments['decoded'];
        },
        'error' => function (Request $request, Response $response) {
            $errormessage = [
                'code' => 403,
                'message' => 'Forbidden',
                'info' => [
                    'message' => 'Please append a token in the correct header'
                ],
            ];
            return $response->withStatus(403)->withJson($errormessage);
        },
    ]));
```
I used PHPStorm [REST Client](https://www.jetbrains.com/help/phpstorm/rest-client-tool-window.html) Testing tools to test my API. I made a correct request and the token was not found. But while i debugged the JwtAuthtentication class, i recognized that the token was found correctly, but not returned. Everything would work, if you add following code on [line 224](https://github.com/tuupola/slim-jwt-auth/blob/2.x/src/JwtAuthentication.php#L224):
```
if (!empty($header)) {
            return $header;
}
```
If this is not the solution, please tell me what i was doing wrong.

**Comment by tuupola** [comment]
Finally got time to look at this. Do I understand correctly the header you are sending looks like this:

```
X-Token: <token>
```

If yes then you should tell the middleware to use custom regexp to extract the token from the header.

```php
$app->add(new Tuupola\Middleware\JwtAuthentication([
    "header" => "X-Token",
    "regexp" => "/(.*)/",
    "secret" => "supersecretkeyyoushouldnotcommittogithub"
]));
```

This is because by default the regexp is `/Bearer\s+(.*)$/i` ie the middleware expects a bearer header:

```
X-Token: Bearer <token>
```

**Comment by tuupola** [comment]
@D4rkMindz ping?

**Comment by D4rkMindz** [comment]
@tuupola sorry i didn't answered until now. 
Thanks for the explanation. This works as expected.

**Comment by tuupola** [comment]
No problem :)
