### ISSUE TITLE
Slim 3 - Fatal error: Cannot use object of type Slim\Http\Request as array

### ISSUE THREAD

**Issue by ronaldo-systemar** [tuupola/slim-jwt-auth#8]
```
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub",
    "callback" => function ($options) use ($app) {
        $app->jwt = $options["decoded"];
    }
]));
```

The example above doesn't work anymore. Maybe Slim 3 is overriding properties or don't allow to set the property. Just to remeber, Slim 3 changed some concepts, since DI container appears, is not possible get app instance like this: **$app = \Slim\Slim::getInstance();**

**Comment by tuupola** [comment]
Use examples from [Slim 3 branch README](https://github.com/tuupola/slim-jwt-auth/blob/slim-3/README.md) instead. Master is currently for Slim 2. 

```php
$app->add(new \Slim\Middleware\JwtAuthentication([
    "secret" => "supersecretkeyyoushouldnotcommittogithub",
    "callback" => function ($request, $response, $arguments) use ($app) {
        $app->jwt = $arguments["decoded"];
    }
]));
```

**Comment by ronaldo-systemar** [comment]
Since we can't get $app instance inside a route callable, what's the purpose of set $app->jwt? Sounds wrong, it's only work at route function() definition.

**Comment by tuupola** [comment]
Callback is just an example and that is how I happen to use it. You can of course store the the decoded value somewhere else. Or you can decide not to store it anywhere at all. 

As the readme says it is up to you to implement how the token data is stored or possible authorization implemented. Middleware itself does only authentication, ie makes sure the passed token is valid. If you want you can use the callback to do something extra with the parsed token. It is up to you.
