### ISSUE TITLE
Insecure use of middleware over HTTP denied by configuration.

### ISSUE THREAD

**Issue by sunildabhi** [tuupola/slim-jwt-auth#81]
Working fine in localhost but when i upload to server it's giving bellow error:

only /token working, all other url have same error

`$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/",
    "passthrough" => ["/token"],
    "secret" => "123456789helo_secret",
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));`

vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php
Line: 110

#0 [internal function]: Slim\Middleware\JwtAuthentication->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#1 /vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Slim\Middleware\JwtAuthentication), Array)
#2 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#3 /vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#4 /vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /vendor/slim/slim/Slim/App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /vendor/slim/slim/Slim/App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /v1/index.php(27): Slim\App->run()
#8 {main}

**Comment by tuupola** [comment]
The copy paste is a trace but does not include the error message. What is the error did you get?

**Comment by tuupola** [comment]
Oh now I see the error message was written in the subject:

_"Insecure use of middleware over HTTP denied by configuration."_

See [security in README](https://github.com/tuupola/slim-jwt-auth#security).

**Comment by sunildabhi** [comment]
thanks "secure" => false fix issue

**Comment by droidwithme** [comment]
Where did you write secure-> false? @sunildabhi
