### ISSUE TITLE
alwasy token not found

### ISSUE THREAD

**Issue by sunildabhi** [tuupola/slim-jwt-auth#82]
check API  it always give error message "Token not found"

i am testing using Postman
1) Authorization Type: Bearer Token
2) Method: POST

`
$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/",
    "passthrough" => ["/login", "/forgot_password"],
    "secret" => '123456789helo_secret',
    "secure" => false,
    "error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->withHeader("Content-Type", "application/json")
            ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));
`

i have also one question, can i use secret from settings using bellow code:
`
$app->getContainer()['settings']['jwt_secret']`

**Comment by tuupola** [comment]
It is better to test with curl. You have better control and understanding what request is actually made.

> i have also one question, can i use secret from settings using bellow code:
$app->getContainer()['settings']['jwt_secret']

What have you tried so far?

**Comment by sunildabhi** [comment]
i also tried with php curl but same issue

`$APIKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MTU4Mzg5NzgsImp0aSI6IjEwZzZkUyIsInN1YiI6Ik56UTBOZz09In0.zRjIqaHZ3U4LMGRhdoDSOr1ZlpQtaI5JklV14DTKvg4';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://gwnks632.haridham.website/v1/change_password");
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: bearer ' . $APIKey));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$curlResult = curl_exec($ch);
curl_close($ch);
echo '<pre>';
print_r($curlResult);
echo '</pre>';`

**Comment by tuupola** [comment]
By curl I meant the [commandline tool](https://curl.haxx.se/docs/manpage.html) not PHP library. For example:

```
$ curl --include --request POST --header "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MTU4Mzg5NzgsImp0aSI6IjEwZzZkUyIsInN1YiI6Ik56UTBOZz09In0.zRjIqaHZ3U4LMGRhdoDSOr1ZlpQtaI5JklV14DTKvg4" http://gwnks632.haridham.website/v1/change_password

HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 15 Jan 2018 11:20:01 GMT
Content-Type: text/html; charset=iso-8859-1
Content-Length: 347
Connection: keep-alive
```

It seems the server returns 400 for empty post.

**Comment by sunildabhi** [comment]
issue fixed when i add RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}] to .htaccess file

**Comment by robm99x** [comment]
On my shared hosting service ionos.com (previously 1and1.com), the Authorization header was being stripped out so I had to add to my {docroot}/public/.htaccess file the following

```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```
