### ISSUE TITLE
Token not found

### ISSUE THREAD

**Issue by pawebgate** [tuupola/slim-jwt-auth#85]
Hi there,
First of all thank you for your contribution. Now, I am testing your slim-basic-auth and it works perfectly fine for me in localhost and live server with https. Now I am testing your slim-jwt-auth and I always get "Token not found" in postman either for localhost or live server. Can you please help me with that and tell me how to set it and test it in postman too?

.htaccess file code : RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

code for jwt auth: 

$container = $app->getContainer();

$container["jwt"] = function ($container) {
    return new StdClass;
};

$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/api",
    "passthrough" => ["/api/token", "/admin/ping"],
	"secure" => true,
	"environment" => "HTTP_X_TOKEN",
	"header" => "X-Token",
	"secret" => "supersecretkeyyoushouldnotcommittogithub",
	"callback" => function ($request, $response, $arguments) use ($container) {
        $container["jwt"] = $arguments["decoded"];
    },
	"error" => function ($request, $response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
        ->withHeader("Content-Type", "application/json")
        ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
    }
]));

$app->add(function($request, $response, $next) {
    $token = $request->getQueryParams()["token"];
    if (false === empty($token)) {
        $request = $request->withHeader("Authorization", "Bearer {$token}");
    }
    return $next($request, $response);
});

Any errors on the above?

**Comment by tuupola** [comment]
Can you show curl request you are doing and response you are receiving.  For example:
 
```
$ curl http://example.com --include  --header "X-Token: yourtokenhere"

**Comment by pawebgate** [comment]
Hi Mikka,

Thanks for answering! I am trying to access 
"https://www.pawebgate.com/slimapp3/public/index.php/api/customers" if that helps, I am doing a GET Request

I just want to combine "https://www.youtube.com/watch?v=DHUxnUX7Y2Y&t=1977s" with your jwt auth. It works perfectly fine when I combine it with your basic auth.

I forgot to mention that I also include the following piece of code right after \Slim\Middleware\JwtAuthentication:

$app->add(function($request, $response, $next) {
    $token = $request->getQueryParams()["token"];
    if (false === empty($token)) {
        $request = $request->withHeader("Authorization", "Bearer {$token}");
    }
    return $next($request, $response);
});

**Comment by tuupola** [comment]
I would debug the code to see what is the actual value of `Authorization` header when it reaches the middleware.

**Comment by pawebgate** [comment]
Well, actually my question is how to set Postman in order to achieve it. If you have any idea it will definitely help.

Yours,

**Comment by tuupola** [comment]
I do not use Postman myself. However I have noticed that people usually find solution to their problem when they test using curl instead.

**Comment by grmxque** [comment]
Hi pawebgate,

Try this : 

![image](https://user-images.githubusercontent.com/12249105/35817412-97415630-0a9d-11e8-8161-448c0991592e.png)
