### ISSUE TITLE
Nginx JWT always return status 401 Unauthorized

### ISSUE THREAD

**Issue by hackerunet** [tuupola/slim-jwt-auth#94]
Dear community, I have been testing for hours using nginx configuration, I have this middleware in slim middleware.php file
```
$app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => ["/api", "/users"],
    "passthrough" => ["/api/auth"],
    "secure" => false,
    "secret" => getenv("JWT_SECRET")
]));
```
And when I access to /api/auth I receive the jwt token which I place inside Authorization Bearer $token, then if I access /users with my header I'm always getting unauthorized error, I'm not receiving anything else, can you please tell me how to rewrite the rules that you use in .htaccess but for nginx ?? I'm not an apache user, just nginx.
Maybe if I'm missing something in the middleware, can you point me to the right direction?
Thanks

**Comment by tuupola** [comment]
Enable logging to see why authorization fails. You could also print out the message in the`error` callback. My guess is the `Authorization` header does not reach Slim.

https://github.com/tuupola/slim-jwt-auth#logger
https://github.com/tuupola/slim-jwt-auth#error

**Comment by hackerunet** [comment]
It was bad expire calculation, your code works well on nginx and apache, even in nginx I did't have to rewrite any rule or tweek anything. Thanks
