### ISSUE TITLE
use container inside callback function

### ISSUE THREAD

**Issue by dpbuzz** [tuupola/slim-jwt-auth#95]
Hi, I have a problem when using container inside callback function. I can't have this code work,  I get "PHP Notice:  Trying to get property of non-object in... " when doing ...$dbObj->get_db()....
 I am doing something wrong?

// database handler
$container['db_handler'] = function ($container) {
    $db = new DB();
    return $db;
};

$app->add(new \Slim\Middleware\JwtAuthentication([
     "secret"       => "supersecretkeyyoushouldnotcommittogithub"
    ,"path"         => "/"
    ,"algorithm"    => ["HS256", "HS512"]
    ,"attribute"    => "jwt"        
    ,"secure"       => true 	  
    ,"callback" => function ($request, $response, $arguments) use ($container) {
    	    $dbObj = $container['db_handler']; // or  $container->get('db_handler')
	    if(!$db=$dbObj->get_db()) {
	    	.....
	    }
    }
]));

**Comment by tuupola** [comment]
Do a `print_r($container['db_handler']);`in the callback to see what is in the container.

**Comment by dpbuzz** [comment]
Hi, thanks doing so let me find the problem!!
One more question, Is there a way to send error message generated inside callback function to the error function? Thanks!

**Comment by tuupola** [comment]
In the callback you should be able set the internal "last error message" property with something like:

```php
$this->message = "Something bad happened";
```
