### ISSUE TITLE
use redirect slim 3 with authorization header

### ISSUE THREAD

**Issue by rakaiathar** [tuupola/slim-jwt-auth#98]
how to use redirect sir, i have try but middleware say token not found, thanks for answer. 
this the code

return $response->withRedirect('/user/home')->withHeader('Authorization', 'Bearer '.$token);

**Comment by tuupola** [comment]
Not possible. Redirect does not work like that. When a browser sees the `Location: /foo/bar` header it simply makes a new `GET /foo/bar` request.

**Comment by rakaiathar** [comment]
thanks for your answer sir, my idea is , when login  and password  true , system will redirect to home user that use slim-jwt-auth on it . generated the token and save locally  with "localStorage.setItem()".  can this idea happen sir?

**Comment by tuupola** [comment]
Correct. You can store the token to localstorage and then include it it `Authorization: Bearer` header when doing a request. You could also store the token to a cookie. Good article about the differences and cotchas is [Where to Store your JWTs – Cookies vs HTML5 Web Storage](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage).

**Comment by rakaiathar** [comment]
ok sir thanks all, i will read it
